/*
 * This file is generated by jOOQ.
 */
package org.gscg.data;


import org.gscg.data.tables.Actor;
import org.gscg.data.tables.ActorParameter;
import org.gscg.data.tables.ActorType;
import org.gscg.data.tables.ActorValue;
import org.gscg.data.tables.AllowedStrategy;
import org.gscg.data.tables.AllowedStrategyCategory;
import org.gscg.data.tables.AllowedStrategyList;
import org.gscg.data.tables.BillOfMaterials;
import org.gscg.data.tables.BomItem;
import org.gscg.data.tables.ChatMessage;
import org.gscg.data.tables.ChosenStrategy;
import org.gscg.data.tables.Event;
import org.gscg.data.tables.ExtraEvent;
import org.gscg.data.tables.ExtraNewsMessage;
import org.gscg.data.tables.GameRole;
import org.gscg.data.tables.GameScenario;
import org.gscg.data.tables.GameSession;
import org.gscg.data.tables.GameSessionGoal;
import org.gscg.data.tables.GameSessionRole;
import org.gscg.data.tables.GameVersion;
import org.gscg.data.tables.GameVersionGoal;
import org.gscg.data.tables.HandledSku;
import org.gscg.data.tables.Handler;
import org.gscg.data.tables.HandlerParameter;
import org.gscg.data.tables.HandlerType;
import org.gscg.data.tables.HandlerValidActor;
import org.gscg.data.tables.HandlerValidActorType;
import org.gscg.data.tables.HandlerValidProduct;
import org.gscg.data.tables.HandlerValue;
import org.gscg.data.tables.ListPage;
import org.gscg.data.tables.Location;
import org.gscg.data.tables.NewsActor;
import org.gscg.data.tables.NewsActorType;
import org.gscg.data.tables.NewsMessage;
import org.gscg.data.tables.OrganizationGame;
import org.gscg.data.tables.OrganizationGameRole;
import org.gscg.data.tables.OrganizationRole;
import org.gscg.data.tables.Player;
import org.gscg.data.tables.PlayerDecision;
import org.gscg.data.tables.PlayerScore;
import org.gscg.data.tables.Process;
import org.gscg.data.tables.ProcessParameter;
import org.gscg.data.tables.ProcessType;
import org.gscg.data.tables.ProcessValue;
import org.gscg.data.tables.Product;
import org.gscg.data.tables.Role;
import org.gscg.data.tables.RoleParameter;
import org.gscg.data.tables.RoleType;
import org.gscg.data.tables.RoleValue;
import org.gscg.data.tables.SentContent;
import org.gscg.data.tables.Transfer;
import org.gscg.data.tables.TriggeredEvent;
import org.gscg.data.tables.TriggeredNewsMessage;
import org.gscg.data.tables.TriggeredProcess;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in gscg.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACTOR_FK_ACTOR_ACTOR_TYPE1_IDX = Internal.createIndex(DSL.name("fk_actor_actor_type1_idx"), Actor.ACTOR, new OrderField[] { Actor.ACTOR.ACTOR_TYPE_ID }, false);
    public static final Index ACTOR_FK_ACTOR_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_actor_game_version1_idx"), Actor.ACTOR, new OrderField[] { Actor.ACTOR.GAME_VERSION_ID }, false);
    public static final Index ACTOR_FK_ACTOR_LOCATION1_IDX = Internal.createIndex(DSL.name("fk_actor_location1_idx"), Actor.ACTOR, new OrderField[] { Actor.ACTOR.LOCATION_ID }, false);
    public static final Index ACTOR_PARAMETER_FK_ACTOR_PARAMETER_ACTOR_TYPE1_IDX = Internal.createIndex(DSL.name("fk_actor_parameter_actor_type1_idx"), ActorParameter.ACTOR_PARAMETER, new OrderField[] { ActorParameter.ACTOR_PARAMETER.ACTOR_TYPE_ID }, false);
    public static final Index ROLE_TYPE_FK_ACTOR_ROLE_ACTOR_TYPE1_IDX = Internal.createIndex(DSL.name("fk_actor_role_actor_type1_idx"), RoleType.ROLE_TYPE, new OrderField[] { RoleType.ROLE_TYPE.ACTOR_TYPE_ID }, false);
    public static final Index ACTOR_TYPE_FK_ACTOR_TYPE_GAME1_IDX = Internal.createIndex(DSL.name("fk_actor_type_game1_idx"), ActorType.ACTOR_TYPE, new OrderField[] { ActorType.ACTOR_TYPE.GAME_ID }, false);
    public static final Index ACTOR_VALUE_FK_ACTOR_VALUE_ACTOR1_IDX = Internal.createIndex(DSL.name("fk_actor_value_actor1_idx"), ActorValue.ACTOR_VALUE, new OrderField[] { ActorValue.ACTOR_VALUE.ACTOR_ID }, false);
    public static final Index ACTOR_VALUE_FK_ACTOR_VALUE_ACTOR_PARAMETER1_IDX = Internal.createIndex(DSL.name("fk_actor_value_actor_parameter1_idx"), ActorValue.ACTOR_VALUE, new OrderField[] { ActorValue.ACTOR_VALUE.ACTOR_PARAMETER_ID }, false);
    public static final Index ALLOWED_STRATEGY_FK_ALLOWED_STRATEGY_ALLOWED_STRATEGY_CATEGORY1_IDX = Internal.createIndex(DSL.name("fk_allowed_strategy_allowed_strategy_category1_idx"), AllowedStrategy.ALLOWED_STRATEGY, new OrderField[] { AllowedStrategy.ALLOWED_STRATEGY.ALLOWED_STRATEGY_CATEGORY_ID }, false);
    public static final Index ALLOWED_STRATEGY_CATEGORY_FK_ALLOWED_STRATEGY_CATEGORY_ALLOWED_STRATEGY_LIST1_IDX = Internal.createIndex(DSL.name("fk_allowed_strategy_category_allowed_strategy_list1_idx"), AllowedStrategyCategory.ALLOWED_STRATEGY_CATEGORY, new OrderField[] { AllowedStrategyCategory.ALLOWED_STRATEGY_CATEGORY.ALLOWED_STRATEGY_LIST_ID }, false);
    public static final Index ALLOWED_STRATEGY_CATEGORY_FK_ALLOWED_STRATEGY_CATEGORY_PAGE1_IDX = Internal.createIndex(DSL.name("fk_allowed_strategy_category_page1_idx"), AllowedStrategyCategory.ALLOWED_STRATEGY_CATEGORY, new OrderField[] { AllowedStrategyCategory.ALLOWED_STRATEGY_CATEGORY.PAGE_ID }, false);
    public static final Index ALLOWED_STRATEGY_LIST_FK_ALLOWED_STRATEGY_LIST_PAGE1_IDX = Internal.createIndex(DSL.name("fk_allowed_strategy_list_page1_idx"), AllowedStrategyList.ALLOWED_STRATEGY_LIST, new OrderField[] { AllowedStrategyList.ALLOWED_STRATEGY_LIST.PAGE_ID }, false);
    public static final Index BILL_OF_MATERIALS_FK_BILL_OF_MATERIALS_PRODUCT1_IDX = Internal.createIndex(DSL.name("fk_bill_of_materials_product1_idx"), BillOfMaterials.BILL_OF_MATERIALS, new OrderField[] { BillOfMaterials.BILL_OF_MATERIALS.PRODUCT_ID }, false);
    public static final Index BOM_ITEM_FK_BOM_ITEM_BILL_OF_MATERIALS1_IDX = Internal.createIndex(DSL.name("fk_bom_item_bill_of_materials1_idx"), BomItem.BOM_ITEM, new OrderField[] { BomItem.BOM_ITEM.BILL_OF_MATERIALS_ID }, false);
    public static final Index BOM_ITEM_FK_BOM_ITEM_PRODUCT1_IDX = Internal.createIndex(DSL.name("fk_bom_item_product1_idx"), BomItem.BOM_ITEM, new OrderField[] { BomItem.BOM_ITEM.PRODUCT_ID }, false);
    public static final Index CHAT_MESSAGE_FK_CHAT_MESSAGE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_chat_message_game_session1_idx"), ChatMessage.CHAT_MESSAGE, new OrderField[] { ChatMessage.CHAT_MESSAGE.GAME_SESSION_ID }, false);
    public static final Index CHAT_MESSAGE_FK_CHAT_MESSAGE_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_chat_message_player1_idx"), ChatMessage.CHAT_MESSAGE, new OrderField[] { ChatMessage.CHAT_MESSAGE.FROM_PLAYER_ID }, false);
    public static final Index CHAT_MESSAGE_FK_CHAT_MESSAGE_PLAYER2_IDX = Internal.createIndex(DSL.name("fk_chat_message_player2_idx"), ChatMessage.CHAT_MESSAGE, new OrderField[] { ChatMessage.CHAT_MESSAGE.TO_PLAYER_ID }, false);
    public static final Index CHOSEN_STRATEGY_FK_CHOSEN_STRATEGY_ALLOWED_STRATEGY1_IDX = Internal.createIndex(DSL.name("fk_chosen_strategy_allowed_strategy1_idx"), ChosenStrategy.CHOSEN_STRATEGY, new OrderField[] { ChosenStrategy.CHOSEN_STRATEGY.ALLOWED_STRATEGY_ID }, false);
    public static final Index CHOSEN_STRATEGY_FK_CHOSEN_STRATEGY_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_chosen_strategy_player1_idx"), ChosenStrategy.CHOSEN_STRATEGY, new OrderField[] { ChosenStrategy.CHOSEN_STRATEGY.PLAYER_ID }, false);
    public static final Index PLAYER_DECISION_FK_CHOSEN_STRATEGY_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_chosen_strategy_player1_idx"), PlayerDecision.PLAYER_DECISION, new OrderField[] { PlayerDecision.PLAYER_DECISION.PLAYER_ID }, false);
    public static final Index EVENT_FK_EVENT_GAME_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_event_game_scenario1_idx"), Event.EVENT, new OrderField[] { Event.EVENT.GAME_SCENARIO_ID }, false);
    public static final Index EVENT_FK_EVENT_NEWS_MESSAGE1_IDX = Internal.createIndex(DSL.name("fk_event_news_message1_idx"), Event.EVENT, new OrderField[] { Event.EVENT.NEWS_MESSAGE_ID }, false);
    public static final Index EVENT_FK_EVENT_TRIGGER_FIXED1_IDX = Internal.createIndex(DSL.name("fk_event_trigger_fixed1_idx"), Event.EVENT, new OrderField[] { Event.EVENT.TRIGGER_FIXED_ID }, false);
    public static final Index EVENT_FK_EVENT_TRIGGER_INTERVAL1_IDX = Internal.createIndex(DSL.name("fk_event_trigger_interval1_idx"), Event.EVENT, new OrderField[] { Event.EVENT.TRIGGER_INTERVAL_ID }, false);
    public static final Index EXTRA_EVENT_FK_EXTRA_NEWS_MESSAGE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_extra_news_message_game_session1_idx"), ExtraEvent.EXTRA_EVENT, new OrderField[] { ExtraEvent.EXTRA_EVENT.GAME_SESSION_ID }, false);
    public static final Index EXTRA_NEWS_MESSAGE_FK_EXTRA_NEWS_MESSAGE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_extra_news_message_game_session1_idx"), ExtraNewsMessage.EXTRA_NEWS_MESSAGE, new OrderField[] { ExtraNewsMessage.EXTRA_NEWS_MESSAGE.GAME_SESSION_ID }, false);
    public static final Index GAME_ROLE_FK_GAME_ROLE_GAME1_IDX = Internal.createIndex(DSL.name("fk_game_role_game1_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.GAME_ID }, false);
    public static final Index GAME_SCENARIO_FK_GAME_SCENARIO_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_game_scenario_game_version1_idx"), GameScenario.GAME_SCENARIO, new OrderField[] { GameScenario.GAME_SCENARIO.GAME_VERSION_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_ALLOWED_STRATEGY_LIST1_IDX = Internal.createIndex(DSL.name("fk_game_session_allowed_strategy_list1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.ALLOWED_STRATEGY_LIST_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_game_session_game_version1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.GAME_VERSION_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_ORGANIZATION_GAME1_IDX = Internal.createIndex(DSL.name("fk_game_session_organization_game1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.ORGANIZATION_GAME_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_PAGE_LIST1_IDX = Internal.createIndex(DSL.name("fk_game_session_page_list1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.BRIEFING_PAGE_LIST_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_PAGE_LIST2_IDX = Internal.createIndex(DSL.name("fk_game_session_page_list2_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.DEBRIEFING_PAGE_LIST_ID }, false);
    public static final Index GAME_SESSION_ROLE_FK_GAME_SESSION_ROLE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_game_session_role_game_session1_idx"), GameSessionRole.GAME_SESSION_ROLE, new OrderField[] { GameSessionRole.GAME_SESSION_ROLE.GAME_SESSION_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_ALLOWED_STRATEGY_LIST1_IDX = Internal.createIndex(DSL.name("fk_game_version_allowed_strategy_list1_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.ALLOWED_STRATEGY_LIST_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_GAME1_IDX = Internal.createIndex(DSL.name("fk_game_version_game1_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.GAME_ID }, false);
    public static final Index GAME_VERSION_GOAL_FK_GAME_VERSION_GOAL_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_game_version_goal_game_version1_idx"), GameVersionGoal.GAME_VERSION_GOAL, new OrderField[] { GameVersionGoal.GAME_VERSION_GOAL.GAME_VERSION_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_PAGE1_IDX = Internal.createIndex(DSL.name("fk_game_version_page1_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.GOAL_PAGE_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_PAGE_LIST1_IDX = Internal.createIndex(DSL.name("fk_game_version_page_list1_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.BRIEFING_PAGE_LIST_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_PAGE_LIST2_IDX = Internal.createIndex(DSL.name("fk_game_version_page_list2_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.DEBRIEFING_PAGE_LIST_ID }, false);
    public static final Index HANDLED_SKU_FK_HANDLED_SKU_SKU1_IDX = Internal.createIndex(DSL.name("fk_handled_sku_sku1_idx"), HandledSku.HANDLED_SKU, new OrderField[] { HandledSku.HANDLED_SKU.SKU_ID }, false);
    public static final Index HANDLED_SKU_FK_HANDLED_SKU_TRANSPORT_MODE1_IDX = Internal.createIndex(DSL.name("fk_handled_sku_transport_mode1_idx"), HandledSku.HANDLED_SKU, new OrderField[] { HandledSku.HANDLED_SKU.TRANSPORT_MODE_ID }, false);
    public static final Index HANDLER_FK_HANDLER_HANDLER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_handler_handler_type1_idx"), Handler.HANDLER, new OrderField[] { Handler.HANDLER.HANDLER_TYPE_ID }, false);
    public static final Index HANDLER_PARAMETER_FK_HANDLER_PARAMETER_HANDLER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_handler_parameter_handler_type1_idx"), HandlerParameter.HANDLER_PARAMETER, new OrderField[] { HandlerParameter.HANDLER_PARAMETER.HANDLER_TYPE_ID }, false);
    public static final Index HANDLER_VALID_ACTOR_FK_HANDLER_PRODUCT_HANDLER1_IDX = Internal.createIndex(DSL.name("fk_handler_product_handler1_idx"), HandlerValidActor.HANDLER_VALID_ACTOR, new OrderField[] { HandlerValidActor.HANDLER_VALID_ACTOR.HANDLER_ID }, false);
    public static final Index HANDLER_VALID_PRODUCT_FK_HANDLER_PRODUCT_HANDLER1_IDX = Internal.createIndex(DSL.name("fk_handler_product_handler1_idx"), HandlerValidProduct.HANDLER_VALID_PRODUCT, new OrderField[] { HandlerValidProduct.HANDLER_VALID_PRODUCT.HANDLER_ID }, false);
    public static final Index HANDLER_VALID_PRODUCT_FK_HANDLER_PRODUCT_PRODUCT1_IDX = Internal.createIndex(DSL.name("fk_handler_product_product1_idx"), HandlerValidProduct.HANDLER_VALID_PRODUCT, new OrderField[] { HandlerValidProduct.HANDLER_VALID_PRODUCT.PRODUCT_ID }, false);
    public static final Index HANDLER_FK_HANDLER_ROLE1_IDX = Internal.createIndex(DSL.name("fk_handler_role1_idx"), Handler.HANDLER, new OrderField[] { Handler.HANDLER.ROLE_ID }, false);
    public static final Index HANDLER_TYPE_FK_HANDLER_TYPE_CONTENT_TYPE1_IDX = Internal.createIndex(DSL.name("fk_handler_type_content_type1_idx"), HandlerType.HANDLER_TYPE, new OrderField[] { HandlerType.HANDLER_TYPE.CONTENT_TYPE_ID }, false);
    public static final Index HANDLER_TYPE_FK_HANDLER_TYPE_ROLE_TYPE1_IDX = Internal.createIndex(DSL.name("fk_handler_type_role_type1_idx"), HandlerType.HANDLER_TYPE, new OrderField[] { HandlerType.HANDLER_TYPE.ROLE_TYPE_ID }, false);
    public static final Index HANDLER_VALID_ACTOR_FK_HANDLER_VALID_ACTOR_ACTOR1_IDX = Internal.createIndex(DSL.name("fk_handler_valid_actor_actor1_idx"), HandlerValidActor.HANDLER_VALID_ACTOR, new OrderField[] { HandlerValidActor.HANDLER_VALID_ACTOR.ACTOR_ID }, false);
    public static final Index HANDLER_VALID_ACTOR_TYPE_FK_HANDLER_VALID_ACTOR_TYPE_ACTOR_TYPE1_IDX = Internal.createIndex(DSL.name("fk_handler_valid_actor_type_actor_type1_idx"), HandlerValidActorType.HANDLER_VALID_ACTOR_TYPE, new OrderField[] { HandlerValidActorType.HANDLER_VALID_ACTOR_TYPE.ACTOR_TYPE_ID }, false);
    public static final Index HANDLER_VALID_ACTOR_TYPE_FK_HANDLER_VALID_ACTOR_TYPE_HANDLER1_IDX = Internal.createIndex(DSL.name("fk_handler_valid_actor_type_handler1_idx"), HandlerValidActorType.HANDLER_VALID_ACTOR_TYPE, new OrderField[] { HandlerValidActorType.HANDLER_VALID_ACTOR_TYPE.HANDLER_ID }, false);
    public static final Index HANDLER_VALUE_FK_HANDLER_VALUE_HANDLER1_IDX = Internal.createIndex(DSL.name("fk_handler_value_handler1_idx"), HandlerValue.HANDLER_VALUE, new OrderField[] { HandlerValue.HANDLER_VALUE.HANDLER_ID }, false);
    public static final Index HANDLER_VALUE_FK_HANDLER_VALUE_HANDLER_PARAMETER1_IDX = Internal.createIndex(DSL.name("fk_handler_value_handler_parameter1_idx"), HandlerValue.HANDLER_VALUE, new OrderField[] { HandlerValue.HANDLER_VALUE.HANDLER_PARAMETER_ID }, false);
    public static final Index LOCATION_FK_LOCATION_LANDMASS1_IDX = Internal.createIndex(DSL.name("fk_location_landmass1_idx"), Location.LOCATION, new OrderField[] { Location.LOCATION.LANDMASS_ID }, false);
    public static final Index NEWS_ACTOR_TYPE_FK_NEWS_ACTOR_TYPE_ACTOR_TYPE1_IDX = Internal.createIndex(DSL.name("fk_news_actor_type_actor_type1_idx"), NewsActorType.NEWS_ACTOR_TYPE, new OrderField[] { NewsActorType.NEWS_ACTOR_TYPE.ACTOR_TYPE_ID }, false);
    public static final Index NEWS_ACTOR_FK_NEWS_ACTOR_TYPE_COPY1_ACTOR1_IDX = Internal.createIndex(DSL.name("fk_news_actor_type_copy1_actor1_idx"), NewsActor.NEWS_ACTOR, new OrderField[] { NewsActor.NEWS_ACTOR.ACTOR_ID }, false);
    public static final Index NEWS_ACTOR_FK_NEWS_ACTOR_TYPE_NEWS_MESSAGE1_IDX = Internal.createIndex(DSL.name("fk_news_actor_type_news_message1_idx"), NewsActor.NEWS_ACTOR, new OrderField[] { NewsActor.NEWS_ACTOR.NEWS_MESSAGE_ID }, false);
    public static final Index NEWS_ACTOR_TYPE_FK_NEWS_ACTOR_TYPE_NEWS_MESSAGE1_IDX = Internal.createIndex(DSL.name("fk_news_actor_type_news_message1_idx"), NewsActorType.NEWS_ACTOR_TYPE, new OrderField[] { NewsActorType.NEWS_ACTOR_TYPE.NEWS_MESSAGE_ID }, false);
    public static final Index NEWS_MESSAGE_FK_NEWS_MESSAGE_GAME_SCENARIO1_IDX = Internal.createIndex(DSL.name("fk_news_message_game_scenario1_idx"), NewsMessage.NEWS_MESSAGE, new OrderField[] { NewsMessage.NEWS_MESSAGE.GAME_SCENARIO_ID }, false);
    public static final Index NEWS_MESSAGE_FK_NEWS_MESSAGE_TRIGGER_FIXED1_IDX = Internal.createIndex(DSL.name("fk_news_message_trigger_fixed1_idx"), NewsMessage.NEWS_MESSAGE, new OrderField[] { NewsMessage.NEWS_MESSAGE.TRIGGER_FIXED_ID }, false);
    public static final Index ORGANIZATION_GAME_FK_ORGANIZATION_GAME_GAME1_IDX = Internal.createIndex(DSL.name("fk_organization_game_game1_idx"), OrganizationGame.ORGANIZATION_GAME, new OrderField[] { OrganizationGame.ORGANIZATION_GAME.GAME_ID }, false);
    public static final Index ORGANIZATION_GAME_FK_ORGANIZATION_GAME_ORGANIZATION1_IDX = Internal.createIndex(DSL.name("fk_organization_game_organization1_idx"), OrganizationGame.ORGANIZATION_GAME, new OrderField[] { OrganizationGame.ORGANIZATION_GAME.ORGANIZATION_ID }, false);
    public static final Index ORGANIZATION_GAME_ROLE_FK_ORGANIZATION_GAME_ROLE_ORGANIZATION_GAME1_IDX = Internal.createIndex(DSL.name("fk_organization_game_role_organization_game1_idx"), OrganizationGameRole.ORGANIZATION_GAME_ROLE, new OrderField[] { OrganizationGameRole.ORGANIZATION_GAME_ROLE.ORGANIZATION_GAME_ID }, false);
    public static final Index ORGANIZATION_GAME_ROLE_FK_ORGANIZATION_GAME_ROLE_USER1_IDX = Internal.createIndex(DSL.name("fk_organization_game_role_user1_idx"), OrganizationGameRole.ORGANIZATION_GAME_ROLE, new OrderField[] { OrganizationGameRole.ORGANIZATION_GAME_ROLE.USER_ID }, false);
    public static final Index ORGANIZATION_ROLE_FK_ORGANIZATION_ROLE_ORGANIZATION1_IDX = Internal.createIndex(DSL.name("fk_organization_role_organization1_idx"), OrganizationRole.ORGANIZATION_ROLE, new OrderField[] { OrganizationRole.ORGANIZATION_ROLE.ORGANIZATION_ID }, false);
    public static final Index GAME_ROLE_FK_ORGANIZATION_ROLE_USER_IDX = Internal.createIndex(DSL.name("fk_organization_role_user_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.USER_ID }, false);
    public static final Index GAME_SESSION_ROLE_FK_ORGANIZATION_ROLE_USER_IDX = Internal.createIndex(DSL.name("fk_organization_role_user_idx"), GameSessionRole.GAME_SESSION_ROLE, new OrderField[] { GameSessionRole.GAME_SESSION_ROLE.USER_ID }, false);
    public static final Index ORGANIZATION_ROLE_FK_ORGANIZATION_ROLE_USER_IDX = Internal.createIndex(DSL.name("fk_organization_role_user_idx"), OrganizationRole.ORGANIZATION_ROLE, new OrderField[] { OrganizationRole.ORGANIZATION_ROLE.USER_ID }, false);
    public static final Index LIST_PAGE_FK_PAGE_PAGE_LIST1_IDX = Internal.createIndex(DSL.name("fk_page_page_list1_idx"), ListPage.LIST_PAGE, new OrderField[] { ListPage.LIST_PAGE.PAGE_LIST_ID }, false);
    public static final Index ACTOR_PARAMETER_FK_PARAMETER_PARAMETER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_parameter_parameter_type1_idx"), ActorParameter.ACTOR_PARAMETER, new OrderField[] { ActorParameter.ACTOR_PARAMETER.PARAMETER_TYPE_ID }, false);
    public static final Index HANDLER_PARAMETER_FK_PARAMETER_PARAMETER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_parameter_parameter_type1_idx"), HandlerParameter.HANDLER_PARAMETER, new OrderField[] { HandlerParameter.HANDLER_PARAMETER.PARAMETER_TYPE_ID }, false);
    public static final Index PROCESS_PARAMETER_FK_PARAMETER_PARAMETER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_parameter_parameter_type1_idx"), ProcessParameter.PROCESS_PARAMETER, new OrderField[] { ProcessParameter.PROCESS_PARAMETER.PARAMETER_TYPE_ID }, false);
    public static final Index PLAYER_FK_PLAYER_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_player_game_session1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GAME_SESSION_ID }, false);
    public static final Index PLAYER_SCORE_FK_PLAYER_SCORE_GOAL1_IDX = Internal.createIndex(DSL.name("fk_player_score_goal1_idx"), PlayerScore.PLAYER_SCORE, new OrderField[] { PlayerScore.PLAYER_SCORE.GOAL_ID }, false);
    public static final Index PLAYER_SCORE_FK_PLAYER_SCORE_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_player_score_player1_idx"), PlayerScore.PLAYER_SCORE, new OrderField[] { PlayerScore.PLAYER_SCORE.PLAYER_ID }, false);
    public static final Index PLAYER_FK_PLAYER_USER1_IDX = Internal.createIndex(DSL.name("fk_player_user1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.USER_ID }, false);
    public static final Index PROCESS_PARAMETER_FK_PROCESS_PARAMETER_PROCESS_TYPE1_IDX = Internal.createIndex(DSL.name("fk_process_parameter_process_type1_idx"), ProcessParameter.PROCESS_PARAMETER, new OrderField[] { ProcessParameter.PROCESS_PARAMETER.PROCESS_TYPE_ID }, false);
    public static final Index PROCESS_FK_PROCESS_PROCESS_TYPE1_IDX = Internal.createIndex(DSL.name("fk_process_process_type1_idx"), Process.PROCESS, new OrderField[] { Process.PROCESS.PROCESS_TYPE_ID }, false);
    public static final Index PROCESS_FK_PROCESS_ROLE1_IDX = Internal.createIndex(DSL.name("fk_process_role1_idx"), Process.PROCESS, new OrderField[] { Process.PROCESS.ROLE_ID }, false);
    public static final Index PROCESS_TYPE_FK_PROCESS_TYPE_ROLE_TYPE1_IDX = Internal.createIndex(DSL.name("fk_process_type_role_type1_idx"), ProcessType.PROCESS_TYPE, new OrderField[] { ProcessType.PROCESS_TYPE.ROLE_TYPE_ID }, false);
    public static final Index PROCESS_VALUE_FK_PROCESS_VALUE_PROCESS1_IDX = Internal.createIndex(DSL.name("fk_process_value_process1_idx"), ProcessValue.PROCESS_VALUE, new OrderField[] { ProcessValue.PROCESS_VALUE.PROCESS_ID }, false);
    public static final Index PROCESS_VALUE_FK_PROCESS_VALUE_PROCESS_PARAMETER1_IDX = Internal.createIndex(DSL.name("fk_process_value_process_parameter1_idx"), ProcessValue.PROCESS_VALUE, new OrderField[] { ProcessValue.PROCESS_VALUE.PROCESS_PARAMETER_ID }, false);
    public static final Index PRODUCT_FK_PRODUCT_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_product_game_version1_idx"), Product.PRODUCT, new OrderField[] { Product.PRODUCT.GAME_VERSION_ID }, false);
    public static final Index PRODUCT_FK_PRODUCT_SKU1_IDX = Internal.createIndex(DSL.name("fk_product_sku1_idx"), Product.PRODUCT, new OrderField[] { Product.PRODUCT.SKU_ID }, false);
    public static final Index ROLE_FK_ROLE_ACTOR1_IDX = Internal.createIndex(DSL.name("fk_role_actor1_idx"), Role.ROLE, new OrderField[] { Role.ROLE.ACTOR_ID }, false);
    public static final Index ROLE_FK_ROLE_CONTENT_RECEIVER1_IDX = Internal.createIndex(DSL.name("fk_role_content_receiver1_idx"), Role.ROLE, new OrderField[] { Role.ROLE.CONTENT_RECEIVER_ID }, false);
    public static final Index ROLE_PARAMETER_FK_ROLE_PARAMETER_PARAMETER_TYPE1_IDX = Internal.createIndex(DSL.name("fk_role_parameter_parameter_type1_idx"), RoleParameter.ROLE_PARAMETER, new OrderField[] { RoleParameter.ROLE_PARAMETER.PARAMETER_TYPE_ID }, false);
    public static final Index ROLE_PARAMETER_FK_ROLE_PARAMETER_ROLE_TYPE1_IDX = Internal.createIndex(DSL.name("fk_role_parameter_role_type1_idx"), RoleParameter.ROLE_PARAMETER, new OrderField[] { RoleParameter.ROLE_PARAMETER.ROLE_TYPE_ID }, false);
    public static final Index ROLE_FK_ROLE_ROLE_TYPE1_IDX = Internal.createIndex(DSL.name("fk_role_role_type1_idx"), Role.ROLE, new OrderField[] { Role.ROLE.ROLE_TYPE_ID }, false);
    public static final Index ROLE_VALUE_FK_ROLE_VALUE_ROLE1_IDX = Internal.createIndex(DSL.name("fk_role_value_role1_idx"), RoleValue.ROLE_VALUE, new OrderField[] { RoleValue.ROLE_VALUE.ROLE_ID }, false);
    public static final Index ROLE_VALUE_FK_ROLE_VALUE_ROLE_PARAMETER1_IDX = Internal.createIndex(DSL.name("fk_role_value_role_parameter1_idx"), RoleValue.ROLE_VALUE, new OrderField[] { RoleValue.ROLE_VALUE.ROLE_PARAMETER_ID }, false);
    public static final Index SENT_CONTENT_FK_SENT_CONTENT_ACTOR1_IDX = Internal.createIndex(DSL.name("fk_sent_content_actor1_idx"), SentContent.SENT_CONTENT, new OrderField[] { SentContent.SENT_CONTENT.FROM_ACTOR_ID }, false);
    public static final Index SENT_CONTENT_FK_SENT_CONTENT_ACTOR2_IDX = Internal.createIndex(DSL.name("fk_sent_content_actor2_idx"), SentContent.SENT_CONTENT, new OrderField[] { SentContent.SENT_CONTENT.TO_ACTOR_ID }, false);
    public static final Index SENT_CONTENT_FK_SENT_CONTENT_CONTENT_TYPE1_IDX = Internal.createIndex(DSL.name("fk_sent_content_content_type1_idx"), SentContent.SENT_CONTENT, new OrderField[] { SentContent.SENT_CONTENT.CONTENT_TYPE_ID }, false);
    public static final Index SENT_CONTENT_FK_SENT_CONTENT_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_sent_content_game_session1_idx"), SentContent.SENT_CONTENT, new OrderField[] { SentContent.SENT_CONTENT.GAME_SESSION_ID }, false);
    public static final Index GAME_SESSION_GOAL_FK_SESSION_GOAL_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_session_goal_game_session1_idx"), GameSessionGoal.GAME_SESSION_GOAL, new OrderField[] { GameSessionGoal.GAME_SESSION_GOAL.GAME_SESSION_ID }, false);
    public static final Index GAME_SESSION_GOAL_FK_SESSION_GOAL_GOAL1_IDX = Internal.createIndex(DSL.name("fk_session_goal_goal1_idx"), GameSessionGoal.GAME_SESSION_GOAL, new OrderField[] { GameSessionGoal.GAME_SESSION_GOAL.GOAL_ID }, false);
    public static final Index GAME_VERSION_GOAL_FK_SESSION_GOAL_GOAL1_IDX = Internal.createIndex(DSL.name("fk_session_goal_goal1_idx"), GameVersionGoal.GAME_VERSION_GOAL, new OrderField[] { GameVersionGoal.GAME_VERSION_GOAL.GOAL_ID }, false);
    public static final Index TRANSFER_FK_TRANSFER_LOCATION1_IDX = Internal.createIndex(DSL.name("fk_transfer_location1_idx"), Transfer.TRANSFER, new OrderField[] { Transfer.TRANSFER.LOCATION2_ID }, false);
    public static final Index TRANSFER_FK_TRANSFER_LOCATION2_IDX = Internal.createIndex(DSL.name("fk_transfer_location2_idx"), Transfer.TRANSFER, new OrderField[] { Transfer.TRANSFER.LOCATION1_ID }, false);
    public static final Index TRANSFER_FK_TRANSFER_TRANSPORT_MODE1_IDX = Internal.createIndex(DSL.name("fk_transfer_transport_mode1_idx"), Transfer.TRANSFER, new OrderField[] { Transfer.TRANSFER.TRANSPORT_MODE_ID }, false);
    public static final Index TRIGGERED_EVENT_FK_TRIGGERED_EVENT_EVENT1_IDX = Internal.createIndex(DSL.name("fk_triggered_event_event1_idx"), TriggeredEvent.TRIGGERED_EVENT, new OrderField[] { TriggeredEvent.TRIGGERED_EVENT.EVENT_ID }, false);
    public static final Index TRIGGERED_EVENT_FK_TRIGGERED_EVENT_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_triggered_event_game_session1_idx"), TriggeredEvent.TRIGGERED_EVENT, new OrderField[] { TriggeredEvent.TRIGGERED_EVENT.GAME_SESSION_ID }, false);
    public static final Index TRIGGERED_NEWS_MESSAGE_FK_TRIGGERED_NEWS_MESSAGE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_triggered_news_message_game_session1_idx"), TriggeredNewsMessage.TRIGGERED_NEWS_MESSAGE, new OrderField[] { TriggeredNewsMessage.TRIGGERED_NEWS_MESSAGE.GAME_SESSION_ID }, false);
    public static final Index TRIGGERED_NEWS_MESSAGE_FK_TRIGGERED_NEWS_MESSAGE_NEWS_MESSAGE1_IDX = Internal.createIndex(DSL.name("fk_triggered_news_message_news_message1_idx"), TriggeredNewsMessage.TRIGGERED_NEWS_MESSAGE, new OrderField[] { TriggeredNewsMessage.TRIGGERED_NEWS_MESSAGE.NEWS_MESSAGE_ID }, false);
    public static final Index TRIGGERED_PROCESS_FK_TRIGGERED_PROCESS_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_triggered_process_game_session1_idx"), TriggeredProcess.TRIGGERED_PROCESS, new OrderField[] { TriggeredProcess.TRIGGERED_PROCESS.GAME_SESSION_ID }, false);
    public static final Index TRIGGERED_PROCESS_FK_TRIGGERED_PROCESS_PROCESS1_IDX = Internal.createIndex(DSL.name("fk_triggered_process_process1_idx"), TriggeredProcess.TRIGGERED_PROCESS, new OrderField[] { TriggeredProcess.TRIGGERED_PROCESS.PROCESS_ID }, false);
}
