/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.ActorParameter;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorParameterRecord extends UpdatableRecordImpl<ActorParameterRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.actor_parameter.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.actor_parameter.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.actor_parameter.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.actor_parameter.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.actor_parameter.default_value</code>.
     */
    public void setDefaultValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.actor_parameter.default_value</code>.
     */
    public String getDefaultValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gscg.actor_parameter.parameter_type_id</code>.
     */
    public void setParameterTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.actor_parameter.parameter_type_id</code>.
     */
    public Integer getParameterTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gscg.actor_parameter.actor_type_id</code>.
     */
    public void setActorTypeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.actor_parameter.actor_type_id</code>.
     */
    public Integer getActorTypeId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ActorParameter.ACTOR_PARAMETER.ID;
    }

    @Override
    public Field<String> field2() {
        return ActorParameter.ACTOR_PARAMETER.NAME;
    }

    @Override
    public Field<String> field3() {
        return ActorParameter.ACTOR_PARAMETER.DEFAULT_VALUE;
    }

    @Override
    public Field<Integer> field4() {
        return ActorParameter.ACTOR_PARAMETER.PARAMETER_TYPE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return ActorParameter.ACTOR_PARAMETER.ACTOR_TYPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDefaultValue();
    }

    @Override
    public Integer component4() {
        return getParameterTypeId();
    }

    @Override
    public Integer component5() {
        return getActorTypeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDefaultValue();
    }

    @Override
    public Integer value4() {
        return getParameterTypeId();
    }

    @Override
    public Integer value5() {
        return getActorTypeId();
    }

    @Override
    public ActorParameterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ActorParameterRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActorParameterRecord value3(String value) {
        setDefaultValue(value);
        return this;
    }

    @Override
    public ActorParameterRecord value4(Integer value) {
        setParameterTypeId(value);
        return this;
    }

    @Override
    public ActorParameterRecord value5(Integer value) {
        setActorTypeId(value);
        return this;
    }

    @Override
    public ActorParameterRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorParameterRecord
     */
    public ActorParameterRecord() {
        super(ActorParameter.ACTOR_PARAMETER);
    }

    /**
     * Create a detached, initialised ActorParameterRecord
     */
    public ActorParameterRecord(Integer id, String name, String defaultValue, Integer parameterTypeId, Integer actorTypeId) {
        super(ActorParameter.ACTOR_PARAMETER);

        setId(id);
        setName(name);
        setDefaultValue(defaultValue);
        setParameterTypeId(parameterTypeId);
        setActorTypeId(actorTypeId);
        resetChangedOnNotNull();
    }
}
