/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.Actor;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorRecord extends UpdatableRecordImpl<ActorRecord> implements Record6<Integer, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.actor.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.actor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.actor.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.actor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.actor.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.actor.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gscg.actor.game_version_id</code>.
     */
    public void setGameVersionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.actor.game_version_id</code>.
     */
    public Integer getGameVersionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gscg.actor.actor_type_id</code>.
     */
    public void setActorTypeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.actor.actor_type_id</code>.
     */
    public Integer getActorTypeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gscg.actor.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.actor.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Actor.ACTOR.ID;
    }

    @Override
    public Field<String> field2() {
        return Actor.ACTOR.NAME;
    }

    @Override
    public Field<String> field3() {
        return Actor.ACTOR.TYPE;
    }

    @Override
    public Field<Integer> field4() {
        return Actor.ACTOR.GAME_VERSION_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Actor.ACTOR.ACTOR_TYPE_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Actor.ACTOR.LOCATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public Integer component4() {
        return getGameVersionId();
    }

    @Override
    public Integer component5() {
        return getActorTypeId();
    }

    @Override
    public Integer component6() {
        return getLocationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public Integer value4() {
        return getGameVersionId();
    }

    @Override
    public Integer value5() {
        return getActorTypeId();
    }

    @Override
    public Integer value6() {
        return getLocationId();
    }

    @Override
    public ActorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ActorRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActorRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public ActorRecord value4(Integer value) {
        setGameVersionId(value);
        return this;
    }

    @Override
    public ActorRecord value5(Integer value) {
        setActorTypeId(value);
        return this;
    }

    @Override
    public ActorRecord value6(Integer value) {
        setLocationId(value);
        return this;
    }

    @Override
    public ActorRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorRecord
     */
    public ActorRecord() {
        super(Actor.ACTOR);
    }

    /**
     * Create a detached, initialised ActorRecord
     */
    public ActorRecord(Integer id, String name, String type, Integer gameVersionId, Integer actorTypeId, Integer locationId) {
        super(Actor.ACTOR);

        setId(id);
        setName(name);
        setType(type);
        setGameVersionId(gameVersionId);
        setActorTypeId(actorTypeId);
        setLocationId(locationId);
        resetChangedOnNotNull();
    }
}
