/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.AllowedStrategyList;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedStrategyListRecord extends UpdatableRecordImpl<AllowedStrategyListRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.allowed_strategy_list.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.allowed_strategy_list.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.allowed_strategy_list.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.allowed_strategy_list.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.allowed_strategy_list.header_html</code>.
     */
    public void setHeaderHtml(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.allowed_strategy_list.header_html</code>.
     */
    public String getHeaderHtml() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gscg.allowed_strategy_list.page_id</code>.
     */
    public void setPageId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.allowed_strategy_list.page_id</code>.
     */
    public Integer getPageId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AllowedStrategyList.ALLOWED_STRATEGY_LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return AllowedStrategyList.ALLOWED_STRATEGY_LIST.NAME;
    }

    @Override
    public Field<String> field3() {
        return AllowedStrategyList.ALLOWED_STRATEGY_LIST.HEADER_HTML;
    }

    @Override
    public Field<Integer> field4() {
        return AllowedStrategyList.ALLOWED_STRATEGY_LIST.PAGE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getHeaderHtml();
    }

    @Override
    public Integer component4() {
        return getPageId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getHeaderHtml();
    }

    @Override
    public Integer value4() {
        return getPageId();
    }

    @Override
    public AllowedStrategyListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AllowedStrategyListRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AllowedStrategyListRecord value3(String value) {
        setHeaderHtml(value);
        return this;
    }

    @Override
    public AllowedStrategyListRecord value4(Integer value) {
        setPageId(value);
        return this;
    }

    @Override
    public AllowedStrategyListRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedStrategyListRecord
     */
    public AllowedStrategyListRecord() {
        super(AllowedStrategyList.ALLOWED_STRATEGY_LIST);
    }

    /**
     * Create a detached, initialised AllowedStrategyListRecord
     */
    public AllowedStrategyListRecord(Integer id, String name, String headerHtml, Integer pageId) {
        super(AllowedStrategyList.ALLOWED_STRATEGY_LIST);

        setId(id);
        setName(name);
        setHeaderHtml(headerHtml);
        setPageId(pageId);
        resetChangedOnNotNull();
    }
}
