/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import java.time.LocalDateTime;

import org.gscg.data.tables.ChatMessage;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatMessageRecord extends UpdatableRecordImpl<ChatMessageRecord> implements Record9<Integer, LocalDateTime, LocalDateTime, String, Byte, Byte, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.chat_message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.chat_message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.chat_message.game_time</code>.
     */
    public void setGameTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.chat_message.game_time</code>.
     */
    public LocalDateTime getGameTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>gscg.chat_message.wall_time</code>.
     */
    public void setWallTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.chat_message.wall_time</code>.
     */
    public LocalDateTime getWallTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>gscg.chat_message.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.chat_message.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gscg.chat_message.from_facilitator</code>.
     */
    public void setFromFacilitator(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.chat_message.from_facilitator</code>.
     */
    public Byte getFromFacilitator() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gscg.chat_message.to_facilitator</code>.
     */
    public void setToFacilitator(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.chat_message.to_facilitator</code>.
     */
    public Byte getToFacilitator() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gscg.chat_message.from_player_id</code>.
     */
    public void setFromPlayerId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gscg.chat_message.from_player_id</code>.
     */
    public Integer getFromPlayerId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gscg.chat_message.to_player_id</code>.
     */
    public void setToPlayerId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gscg.chat_message.to_player_id</code>.
     */
    public Integer getToPlayerId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gscg.chat_message.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gscg.chat_message.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, LocalDateTime, LocalDateTime, String, Byte, Byte, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, LocalDateTime, LocalDateTime, String, Byte, Byte, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChatMessage.CHAT_MESSAGE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ChatMessage.CHAT_MESSAGE.GAME_TIME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ChatMessage.CHAT_MESSAGE.WALL_TIME;
    }

    @Override
    public Field<String> field4() {
        return ChatMessage.CHAT_MESSAGE.CONTENT;
    }

    @Override
    public Field<Byte> field5() {
        return ChatMessage.CHAT_MESSAGE.FROM_FACILITATOR;
    }

    @Override
    public Field<Byte> field6() {
        return ChatMessage.CHAT_MESSAGE.TO_FACILITATOR;
    }

    @Override
    public Field<Integer> field7() {
        return ChatMessage.CHAT_MESSAGE.FROM_PLAYER_ID;
    }

    @Override
    public Field<Integer> field8() {
        return ChatMessage.CHAT_MESSAGE.TO_PLAYER_ID;
    }

    @Override
    public Field<Integer> field9() {
        return ChatMessage.CHAT_MESSAGE.GAME_SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getGameTime();
    }

    @Override
    public LocalDateTime component3() {
        return getWallTime();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public Byte component5() {
        return getFromFacilitator();
    }

    @Override
    public Byte component6() {
        return getToFacilitator();
    }

    @Override
    public Integer component7() {
        return getFromPlayerId();
    }

    @Override
    public Integer component8() {
        return getToPlayerId();
    }

    @Override
    public Integer component9() {
        return getGameSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getGameTime();
    }

    @Override
    public LocalDateTime value3() {
        return getWallTime();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public Byte value5() {
        return getFromFacilitator();
    }

    @Override
    public Byte value6() {
        return getToFacilitator();
    }

    @Override
    public Integer value7() {
        return getFromPlayerId();
    }

    @Override
    public Integer value8() {
        return getToPlayerId();
    }

    @Override
    public Integer value9() {
        return getGameSessionId();
    }

    @Override
    public ChatMessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChatMessageRecord value2(LocalDateTime value) {
        setGameTime(value);
        return this;
    }

    @Override
    public ChatMessageRecord value3(LocalDateTime value) {
        setWallTime(value);
        return this;
    }

    @Override
    public ChatMessageRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ChatMessageRecord value5(Byte value) {
        setFromFacilitator(value);
        return this;
    }

    @Override
    public ChatMessageRecord value6(Byte value) {
        setToFacilitator(value);
        return this;
    }

    @Override
    public ChatMessageRecord value7(Integer value) {
        setFromPlayerId(value);
        return this;
    }

    @Override
    public ChatMessageRecord value8(Integer value) {
        setToPlayerId(value);
        return this;
    }

    @Override
    public ChatMessageRecord value9(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public ChatMessageRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, String value4, Byte value5, Byte value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatMessageRecord
     */
    public ChatMessageRecord() {
        super(ChatMessage.CHAT_MESSAGE);
    }

    /**
     * Create a detached, initialised ChatMessageRecord
     */
    public ChatMessageRecord(Integer id, LocalDateTime gameTime, LocalDateTime wallTime, String content, Byte fromFacilitator, Byte toFacilitator, Integer fromPlayerId, Integer toPlayerId, Integer gameSessionId) {
        super(ChatMessage.CHAT_MESSAGE);

        setId(id);
        setGameTime(gameTime);
        setWallTime(wallTime);
        setContent(content);
        setFromFacilitator(fromFacilitator);
        setToFacilitator(toFacilitator);
        setFromPlayerId(fromPlayerId);
        setToPlayerId(toPlayerId);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
