/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import java.time.LocalTime;

import org.gscg.data.tables.ContentReceiver;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentReceiverRecord extends UpdatableRecordImpl<ContentReceiverRecord> implements Record19<Integer, String, Double, String, String, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.content_receiver.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.content_receiver.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.content_receiver.delay_time</code>.
     */
    public void setDelayTime(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.delay_time</code>.
     */
    public Double getDelayTime() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>gscg.content_receiver.delay_time_dist</code>.
     */
    public void setDelayTimeDist(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.delay_time_dist</code>.
     */
    public String getDelayTimeDist() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gscg.content_receiver.delay_time_unit</code>.
     */
    public void setDelayTimeUnit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.delay_time_unit</code>.
     */
    public String getDelayTimeUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_mo</code>.
     */
    public void setWorkHoursStartMo(LocalTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_mo</code>.
     */
    public LocalTime getWorkHoursStartMo() {
        return (LocalTime) get(5);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_mo</code>.
     */
    public void setWorkHoursEndMo(LocalTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_mo</code>.
     */
    public LocalTime getWorkHoursEndMo() {
        return (LocalTime) get(6);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_tu</code>.
     */
    public void setWorkHoursStartTu(LocalTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_tu</code>.
     */
    public LocalTime getWorkHoursStartTu() {
        return (LocalTime) get(7);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_tu</code>.
     */
    public void setWorkHoursEndTu(LocalTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_tu</code>.
     */
    public LocalTime getWorkHoursEndTu() {
        return (LocalTime) get(8);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_we</code>.
     */
    public void setWorkHoursStartWe(LocalTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_we</code>.
     */
    public LocalTime getWorkHoursStartWe() {
        return (LocalTime) get(9);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_we</code>.
     */
    public void setWorkHoursEndWe(LocalTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_we</code>.
     */
    public LocalTime getWorkHoursEndWe() {
        return (LocalTime) get(10);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_th</code>.
     */
    public void setWorkHoursStartTh(LocalTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_th</code>.
     */
    public LocalTime getWorkHoursStartTh() {
        return (LocalTime) get(11);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_th</code>.
     */
    public void setWorkHoursEndTh(LocalTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_th</code>.
     */
    public LocalTime getWorkHoursEndTh() {
        return (LocalTime) get(12);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_fr</code>.
     */
    public void setWorkHoursStartFr(LocalTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_fr</code>.
     */
    public LocalTime getWorkHoursStartFr() {
        return (LocalTime) get(13);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_fr</code>.
     */
    public void setWorkHoursEndFr(LocalTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_fr</code>.
     */
    public LocalTime getWorkHoursEndFr() {
        return (LocalTime) get(14);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_sa</code>.
     */
    public void setWorkHoursStartSa(LocalTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_sa</code>.
     */
    public LocalTime getWorkHoursStartSa() {
        return (LocalTime) get(15);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_sa</code>.
     */
    public void setWorkHoursEndSa(LocalTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_sa</code>.
     */
    public LocalTime getWorkHoursEndSa() {
        return (LocalTime) get(16);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_start_su</code>.
     */
    public void setWorkHoursStartSu(LocalTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_start_su</code>.
     */
    public LocalTime getWorkHoursStartSu() {
        return (LocalTime) get(17);
    }

    /**
     * Setter for <code>gscg.content_receiver.work_hours_end_su</code>.
     */
    public void setWorkHoursEndSu(LocalTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>gscg.content_receiver.work_hours_end_su</code>.
     */
    public LocalTime getWorkHoursEndSu() {
        return (LocalTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Integer, String, Double, String, String, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Integer, String, Double, String, String, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime, LocalTime> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ContentReceiver.CONTENT_RECEIVER.ID;
    }

    @Override
    public Field<String> field2() {
        return ContentReceiver.CONTENT_RECEIVER.NAME;
    }

    @Override
    public Field<Double> field3() {
        return ContentReceiver.CONTENT_RECEIVER.DELAY_TIME;
    }

    @Override
    public Field<String> field4() {
        return ContentReceiver.CONTENT_RECEIVER.DELAY_TIME_DIST;
    }

    @Override
    public Field<String> field5() {
        return ContentReceiver.CONTENT_RECEIVER.DELAY_TIME_UNIT;
    }

    @Override
    public Field<LocalTime> field6() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_MO;
    }

    @Override
    public Field<LocalTime> field7() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_MO;
    }

    @Override
    public Field<LocalTime> field8() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_TU;
    }

    @Override
    public Field<LocalTime> field9() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_TU;
    }

    @Override
    public Field<LocalTime> field10() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_WE;
    }

    @Override
    public Field<LocalTime> field11() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_WE;
    }

    @Override
    public Field<LocalTime> field12() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_TH;
    }

    @Override
    public Field<LocalTime> field13() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_TH;
    }

    @Override
    public Field<LocalTime> field14() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_FR;
    }

    @Override
    public Field<LocalTime> field15() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_FR;
    }

    @Override
    public Field<LocalTime> field16() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_SA;
    }

    @Override
    public Field<LocalTime> field17() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_SA;
    }

    @Override
    public Field<LocalTime> field18() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_START_SU;
    }

    @Override
    public Field<LocalTime> field19() {
        return ContentReceiver.CONTENT_RECEIVER.WORK_HOURS_END_SU;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getDelayTime();
    }

    @Override
    public String component4() {
        return getDelayTimeDist();
    }

    @Override
    public String component5() {
        return getDelayTimeUnit();
    }

    @Override
    public LocalTime component6() {
        return getWorkHoursStartMo();
    }

    @Override
    public LocalTime component7() {
        return getWorkHoursEndMo();
    }

    @Override
    public LocalTime component8() {
        return getWorkHoursStartTu();
    }

    @Override
    public LocalTime component9() {
        return getWorkHoursEndTu();
    }

    @Override
    public LocalTime component10() {
        return getWorkHoursStartWe();
    }

    @Override
    public LocalTime component11() {
        return getWorkHoursEndWe();
    }

    @Override
    public LocalTime component12() {
        return getWorkHoursStartTh();
    }

    @Override
    public LocalTime component13() {
        return getWorkHoursEndTh();
    }

    @Override
    public LocalTime component14() {
        return getWorkHoursStartFr();
    }

    @Override
    public LocalTime component15() {
        return getWorkHoursEndFr();
    }

    @Override
    public LocalTime component16() {
        return getWorkHoursStartSa();
    }

    @Override
    public LocalTime component17() {
        return getWorkHoursEndSa();
    }

    @Override
    public LocalTime component18() {
        return getWorkHoursStartSu();
    }

    @Override
    public LocalTime component19() {
        return getWorkHoursEndSu();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getDelayTime();
    }

    @Override
    public String value4() {
        return getDelayTimeDist();
    }

    @Override
    public String value5() {
        return getDelayTimeUnit();
    }

    @Override
    public LocalTime value6() {
        return getWorkHoursStartMo();
    }

    @Override
    public LocalTime value7() {
        return getWorkHoursEndMo();
    }

    @Override
    public LocalTime value8() {
        return getWorkHoursStartTu();
    }

    @Override
    public LocalTime value9() {
        return getWorkHoursEndTu();
    }

    @Override
    public LocalTime value10() {
        return getWorkHoursStartWe();
    }

    @Override
    public LocalTime value11() {
        return getWorkHoursEndWe();
    }

    @Override
    public LocalTime value12() {
        return getWorkHoursStartTh();
    }

    @Override
    public LocalTime value13() {
        return getWorkHoursEndTh();
    }

    @Override
    public LocalTime value14() {
        return getWorkHoursStartFr();
    }

    @Override
    public LocalTime value15() {
        return getWorkHoursEndFr();
    }

    @Override
    public LocalTime value16() {
        return getWorkHoursStartSa();
    }

    @Override
    public LocalTime value17() {
        return getWorkHoursEndSa();
    }

    @Override
    public LocalTime value18() {
        return getWorkHoursStartSu();
    }

    @Override
    public LocalTime value19() {
        return getWorkHoursEndSu();
    }

    @Override
    public ContentReceiverRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value3(Double value) {
        setDelayTime(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value4(String value) {
        setDelayTimeDist(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value5(String value) {
        setDelayTimeUnit(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value6(LocalTime value) {
        setWorkHoursStartMo(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value7(LocalTime value) {
        setWorkHoursEndMo(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value8(LocalTime value) {
        setWorkHoursStartTu(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value9(LocalTime value) {
        setWorkHoursEndTu(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value10(LocalTime value) {
        setWorkHoursStartWe(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value11(LocalTime value) {
        setWorkHoursEndWe(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value12(LocalTime value) {
        setWorkHoursStartTh(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value13(LocalTime value) {
        setWorkHoursEndTh(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value14(LocalTime value) {
        setWorkHoursStartFr(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value15(LocalTime value) {
        setWorkHoursEndFr(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value16(LocalTime value) {
        setWorkHoursStartSa(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value17(LocalTime value) {
        setWorkHoursEndSa(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value18(LocalTime value) {
        setWorkHoursStartSu(value);
        return this;
    }

    @Override
    public ContentReceiverRecord value19(LocalTime value) {
        setWorkHoursEndSu(value);
        return this;
    }

    @Override
    public ContentReceiverRecord values(Integer value1, String value2, Double value3, String value4, String value5, LocalTime value6, LocalTime value7, LocalTime value8, LocalTime value9, LocalTime value10, LocalTime value11, LocalTime value12, LocalTime value13, LocalTime value14, LocalTime value15, LocalTime value16, LocalTime value17, LocalTime value18, LocalTime value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentReceiverRecord
     */
    public ContentReceiverRecord() {
        super(ContentReceiver.CONTENT_RECEIVER);
    }

    /**
     * Create a detached, initialised ContentReceiverRecord
     */
    public ContentReceiverRecord(Integer id, String name, Double delayTime, String delayTimeDist, String delayTimeUnit, LocalTime workHoursStartMo, LocalTime workHoursEndMo, LocalTime workHoursStartTu, LocalTime workHoursEndTu, LocalTime workHoursStartWe, LocalTime workHoursEndWe, LocalTime workHoursStartTh, LocalTime workHoursEndTh, LocalTime workHoursStartFr, LocalTime workHoursEndFr, LocalTime workHoursStartSa, LocalTime workHoursEndSa, LocalTime workHoursStartSu, LocalTime workHoursEndSu) {
        super(ContentReceiver.CONTENT_RECEIVER);

        setId(id);
        setName(name);
        setDelayTime(delayTime);
        setDelayTimeDist(delayTimeDist);
        setDelayTimeUnit(delayTimeUnit);
        setWorkHoursStartMo(workHoursStartMo);
        setWorkHoursEndMo(workHoursEndMo);
        setWorkHoursStartTu(workHoursStartTu);
        setWorkHoursEndTu(workHoursEndTu);
        setWorkHoursStartWe(workHoursStartWe);
        setWorkHoursEndWe(workHoursEndWe);
        setWorkHoursStartTh(workHoursStartTh);
        setWorkHoursEndTh(workHoursEndTh);
        setWorkHoursStartFr(workHoursStartFr);
        setWorkHoursEndFr(workHoursEndFr);
        setWorkHoursStartSa(workHoursStartSa);
        setWorkHoursEndSa(workHoursEndSa);
        setWorkHoursStartSu(workHoursStartSu);
        setWorkHoursEndSu(workHoursEndSu);
        resetChangedOnNotNull();
    }
}
