/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import java.time.LocalDateTime;

import org.gscg.data.tables.ExtraEvent;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExtraEventRecord extends UpdatableRecordImpl<ExtraEventRecord> implements Record10<Integer, LocalDateTime, LocalDateTime, String, Integer, String, Byte, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.extra_event.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.extra_event.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.extra_event.game_time</code>.
     */
    public void setGameTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.extra_event.game_time</code>.
     */
    public LocalDateTime getGameTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>gscg.extra_event.wall_time</code>.
     */
    public void setWallTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.extra_event.wall_time</code>.
     */
    public LocalDateTime getWallTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>gscg.extra_event.object_type</code>.
     */
    public void setObjectType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.extra_event.object_type</code>.
     */
    public String getObjectType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gscg.extra_event.object_id</code>.
     */
    public void setObjectId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.extra_event.object_id</code>.
     */
    public Integer getObjectId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gscg.extra_event.object_name</code>.
     */
    public void setObjectName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.extra_event.object_name</code>.
     */
    public String getObjectName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gscg.extra_event.object_available</code>.
     */
    public void setObjectAvailable(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>gscg.extra_event.object_available</code>.
     */
    public Byte getObjectAvailable() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>gscg.extra_event.parameter_name</code>.
     */
    public void setParameterName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gscg.extra_event.parameter_name</code>.
     */
    public String getParameterName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gscg.extra_event.parameter_value</code>.
     */
    public void setParameterValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gscg.extra_event.parameter_value</code>.
     */
    public String getParameterValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gscg.extra_event.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>gscg.extra_event.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, LocalDateTime, LocalDateTime, String, Integer, String, Byte, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, LocalDateTime, LocalDateTime, String, Integer, String, Byte, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ExtraEvent.EXTRA_EVENT.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ExtraEvent.EXTRA_EVENT.GAME_TIME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ExtraEvent.EXTRA_EVENT.WALL_TIME;
    }

    @Override
    public Field<String> field4() {
        return ExtraEvent.EXTRA_EVENT.OBJECT_TYPE;
    }

    @Override
    public Field<Integer> field5() {
        return ExtraEvent.EXTRA_EVENT.OBJECT_ID;
    }

    @Override
    public Field<String> field6() {
        return ExtraEvent.EXTRA_EVENT.OBJECT_NAME;
    }

    @Override
    public Field<Byte> field7() {
        return ExtraEvent.EXTRA_EVENT.OBJECT_AVAILABLE;
    }

    @Override
    public Field<String> field8() {
        return ExtraEvent.EXTRA_EVENT.PARAMETER_NAME;
    }

    @Override
    public Field<String> field9() {
        return ExtraEvent.EXTRA_EVENT.PARAMETER_VALUE;
    }

    @Override
    public Field<Integer> field10() {
        return ExtraEvent.EXTRA_EVENT.GAME_SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getGameTime();
    }

    @Override
    public LocalDateTime component3() {
        return getWallTime();
    }

    @Override
    public String component4() {
        return getObjectType();
    }

    @Override
    public Integer component5() {
        return getObjectId();
    }

    @Override
    public String component6() {
        return getObjectName();
    }

    @Override
    public Byte component7() {
        return getObjectAvailable();
    }

    @Override
    public String component8() {
        return getParameterName();
    }

    @Override
    public String component9() {
        return getParameterValue();
    }

    @Override
    public Integer component10() {
        return getGameSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getGameTime();
    }

    @Override
    public LocalDateTime value3() {
        return getWallTime();
    }

    @Override
    public String value4() {
        return getObjectType();
    }

    @Override
    public Integer value5() {
        return getObjectId();
    }

    @Override
    public String value6() {
        return getObjectName();
    }

    @Override
    public Byte value7() {
        return getObjectAvailable();
    }

    @Override
    public String value8() {
        return getParameterName();
    }

    @Override
    public String value9() {
        return getParameterValue();
    }

    @Override
    public Integer value10() {
        return getGameSessionId();
    }

    @Override
    public ExtraEventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ExtraEventRecord value2(LocalDateTime value) {
        setGameTime(value);
        return this;
    }

    @Override
    public ExtraEventRecord value3(LocalDateTime value) {
        setWallTime(value);
        return this;
    }

    @Override
    public ExtraEventRecord value4(String value) {
        setObjectType(value);
        return this;
    }

    @Override
    public ExtraEventRecord value5(Integer value) {
        setObjectId(value);
        return this;
    }

    @Override
    public ExtraEventRecord value6(String value) {
        setObjectName(value);
        return this;
    }

    @Override
    public ExtraEventRecord value7(Byte value) {
        setObjectAvailable(value);
        return this;
    }

    @Override
    public ExtraEventRecord value8(String value) {
        setParameterName(value);
        return this;
    }

    @Override
    public ExtraEventRecord value9(String value) {
        setParameterValue(value);
        return this;
    }

    @Override
    public ExtraEventRecord value10(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public ExtraEventRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, String value4, Integer value5, String value6, Byte value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExtraEventRecord
     */
    public ExtraEventRecord() {
        super(ExtraEvent.EXTRA_EVENT);
    }

    /**
     * Create a detached, initialised ExtraEventRecord
     */
    public ExtraEventRecord(Integer id, LocalDateTime gameTime, LocalDateTime wallTime, String objectType, Integer objectId, String objectName, Byte objectAvailable, String parameterName, String parameterValue, Integer gameSessionId) {
        super(ExtraEvent.EXTRA_EVENT);

        setId(id);
        setGameTime(gameTime);
        setWallTime(wallTime);
        setObjectType(objectType);
        setObjectId(objectId);
        setObjectName(objectName);
        setObjectAvailable(objectAvailable);
        setParameterName(parameterName);
        setParameterValue(parameterValue);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
