/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.GameVersionGoal;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameVersionGoalRecord extends UpdatableRecordImpl<GameVersionGoalRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.game_version_goal.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.game_version_goal.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.game_version_goal.explanation</code>.
     */
    public void setExplanation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.game_version_goal.explanation</code>.
     */
    public String getExplanation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.game_version_goal.goal_id</code>.
     */
    public void setGoalId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.game_version_goal.goal_id</code>.
     */
    public Integer getGoalId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gscg.game_version_goal.game_version_id</code>.
     */
    public void setGameVersionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.game_version_goal.game_version_id</code>.
     */
    public Integer getGameVersionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GameVersionGoal.GAME_VERSION_GOAL.ID;
    }

    @Override
    public Field<String> field2() {
        return GameVersionGoal.GAME_VERSION_GOAL.EXPLANATION;
    }

    @Override
    public Field<Integer> field3() {
        return GameVersionGoal.GAME_VERSION_GOAL.GOAL_ID;
    }

    @Override
    public Field<Integer> field4() {
        return GameVersionGoal.GAME_VERSION_GOAL.GAME_VERSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getExplanation();
    }

    @Override
    public Integer component3() {
        return getGoalId();
    }

    @Override
    public Integer component4() {
        return getGameVersionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getExplanation();
    }

    @Override
    public Integer value3() {
        return getGoalId();
    }

    @Override
    public Integer value4() {
        return getGameVersionId();
    }

    @Override
    public GameVersionGoalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameVersionGoalRecord value2(String value) {
        setExplanation(value);
        return this;
    }

    @Override
    public GameVersionGoalRecord value3(Integer value) {
        setGoalId(value);
        return this;
    }

    @Override
    public GameVersionGoalRecord value4(Integer value) {
        setGameVersionId(value);
        return this;
    }

    @Override
    public GameVersionGoalRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameVersionGoalRecord
     */
    public GameVersionGoalRecord() {
        super(GameVersionGoal.GAME_VERSION_GOAL);
    }

    /**
     * Create a detached, initialised GameVersionGoalRecord
     */
    public GameVersionGoalRecord(Integer id, String explanation, Integer goalId, Integer gameVersionId) {
        super(GameVersionGoal.GAME_VERSION_GOAL);

        setId(id);
        setExplanation(explanation);
        setGoalId(goalId);
        setGameVersionId(gameVersionId);
        resetChangedOnNotNull();
    }
}
