/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.GameVersion;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameVersionRecord extends UpdatableRecordImpl<GameVersionRecord> implements Record10<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.game_version.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.game_version.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.game_version.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.game_version.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.game_version.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.game_version.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gscg.game_version.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.game_version.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gscg.game_version.archived</code>.
     */
    public void setArchived(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.game_version.archived</code>.
     */
    public Byte getArchived() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gscg.game_version.briefing_page_list_id</code>.
     */
    public void setBriefingPageListId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.game_version.briefing_page_list_id</code>.
     */
    public Integer getBriefingPageListId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gscg.game_version.debriefing_page_list_id</code>.
     */
    public void setDebriefingPageListId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gscg.game_version.debriefing_page_list_id</code>.
     */
    public Integer getDebriefingPageListId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gscg.game_version.allowed_strategy_list_id</code>.
     */
    public void setAllowedStrategyListId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gscg.game_version.allowed_strategy_list_id</code>.
     */
    public Integer getAllowedStrategyListId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gscg.game_version.goal_page_id</code>.
     */
    public void setGoalPageId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gscg.game_version.goal_page_id</code>.
     */
    public Integer getGoalPageId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>gscg.game_version.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>gscg.game_version.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GameVersion.GAME_VERSION.ID;
    }

    @Override
    public Field<String> field2() {
        return GameVersion.GAME_VERSION.CODE;
    }

    @Override
    public Field<String> field3() {
        return GameVersion.GAME_VERSION.NAME;
    }

    @Override
    public Field<String> field4() {
        return GameVersion.GAME_VERSION.DESCRIPTION;
    }

    @Override
    public Field<Byte> field5() {
        return GameVersion.GAME_VERSION.ARCHIVED;
    }

    @Override
    public Field<Integer> field6() {
        return GameVersion.GAME_VERSION.BRIEFING_PAGE_LIST_ID;
    }

    @Override
    public Field<Integer> field7() {
        return GameVersion.GAME_VERSION.DEBRIEFING_PAGE_LIST_ID;
    }

    @Override
    public Field<Integer> field8() {
        return GameVersion.GAME_VERSION.ALLOWED_STRATEGY_LIST_ID;
    }

    @Override
    public Field<Integer> field9() {
        return GameVersion.GAME_VERSION.GOAL_PAGE_ID;
    }

    @Override
    public Field<Integer> field10() {
        return GameVersion.GAME_VERSION.GAME_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Byte component5() {
        return getArchived();
    }

    @Override
    public Integer component6() {
        return getBriefingPageListId();
    }

    @Override
    public Integer component7() {
        return getDebriefingPageListId();
    }

    @Override
    public Integer component8() {
        return getAllowedStrategyListId();
    }

    @Override
    public Integer component9() {
        return getGoalPageId();
    }

    @Override
    public Integer component10() {
        return getGameId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Byte value5() {
        return getArchived();
    }

    @Override
    public Integer value6() {
        return getBriefingPageListId();
    }

    @Override
    public Integer value7() {
        return getDebriefingPageListId();
    }

    @Override
    public Integer value8() {
        return getAllowedStrategyListId();
    }

    @Override
    public Integer value9() {
        return getGoalPageId();
    }

    @Override
    public Integer value10() {
        return getGameId();
    }

    @Override
    public GameVersionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameVersionRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public GameVersionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GameVersionRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GameVersionRecord value5(Byte value) {
        setArchived(value);
        return this;
    }

    @Override
    public GameVersionRecord value6(Integer value) {
        setBriefingPageListId(value);
        return this;
    }

    @Override
    public GameVersionRecord value7(Integer value) {
        setDebriefingPageListId(value);
        return this;
    }

    @Override
    public GameVersionRecord value8(Integer value) {
        setAllowedStrategyListId(value);
        return this;
    }

    @Override
    public GameVersionRecord value9(Integer value) {
        setGoalPageId(value);
        return this;
    }

    @Override
    public GameVersionRecord value10(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameVersionRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameVersionRecord
     */
    public GameVersionRecord() {
        super(GameVersion.GAME_VERSION);
    }

    /**
     * Create a detached, initialised GameVersionRecord
     */
    public GameVersionRecord(Integer id, String code, String name, String description, Byte archived, Integer briefingPageListId, Integer debriefingPageListId, Integer allowedStrategyListId, Integer goalPageId, Integer gameId) {
        super(GameVersion.GAME_VERSION);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setArchived(archived);
        setBriefingPageListId(briefingPageListId);
        setDebriefingPageListId(debriefingPageListId);
        setAllowedStrategyListId(allowedStrategyListId);
        setGoalPageId(goalPageId);
        setGameId(gameId);
        resetChangedOnNotNull();
    }
}
