/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.GameSessionRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameSessionRoleRecord extends UpdatableRecordImpl<GameSessionRoleRecord> implements Record4<Integer, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.game_session_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.game_session_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.game_session_role.facilitator</code>.
     */
    public void setFacilitator(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.game_session_role.facilitator</code>.
     */
    public Byte getFacilitator() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gscg.game_session_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.game_session_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gscg.game_session_role.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.game_session_role.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Byte, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Byte, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GameSessionRole.GAME_SESSION_ROLE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return GameSessionRole.GAME_SESSION_ROLE.FACILITATOR;
    }

    @Override
    public Field<Integer> field3() {
        return GameSessionRole.GAME_SESSION_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return GameSessionRole.GAME_SESSION_ROLE.GAME_SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getFacilitator();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getGameSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getFacilitator();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getGameSessionId();
    }

    @Override
    public GameSessionRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameSessionRoleRecord value2(Byte value) {
        setFacilitator(value);
        return this;
    }

    @Override
    public GameSessionRoleRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public GameSessionRoleRecord value4(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public GameSessionRoleRecord values(Integer value1, Byte value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameSessionRoleRecord
     */
    public GameSessionRoleRecord() {
        super(GameSessionRole.GAME_SESSION_ROLE);
    }

    /**
     * Create a detached, initialised GameSessionRoleRecord
     */
    public GameSessionRoleRecord(Integer id, Byte facilitator, Integer userId, Integer gameSessionId) {
        super(GameSessionRole.GAME_SESSION_ROLE);

        setId(id);
        setFacilitator(facilitator);
        setUserId(userId);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
