/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.GameSessionGoal;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameSessionGoalRecord extends UpdatableRecordImpl<GameSessionGoalRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.game_session_goal.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.game_session_goal.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.game_session_goal.explanation</code>.
     */
    public void setExplanation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.game_session_goal.explanation</code>.
     */
    public String getExplanation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.game_session_goal.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.game_session_goal.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gscg.game_session_goal.goal_id</code>.
     */
    public void setGoalId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.game_session_goal.goal_id</code>.
     */
    public Integer getGoalId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GameSessionGoal.GAME_SESSION_GOAL.ID;
    }

    @Override
    public Field<String> field2() {
        return GameSessionGoal.GAME_SESSION_GOAL.EXPLANATION;
    }

    @Override
    public Field<Integer> field3() {
        return GameSessionGoal.GAME_SESSION_GOAL.GAME_SESSION_ID;
    }

    @Override
    public Field<Integer> field4() {
        return GameSessionGoal.GAME_SESSION_GOAL.GOAL_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getExplanation();
    }

    @Override
    public Integer component3() {
        return getGameSessionId();
    }

    @Override
    public Integer component4() {
        return getGoalId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getExplanation();
    }

    @Override
    public Integer value3() {
        return getGameSessionId();
    }

    @Override
    public Integer value4() {
        return getGoalId();
    }

    @Override
    public GameSessionGoalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameSessionGoalRecord value2(String value) {
        setExplanation(value);
        return this;
    }

    @Override
    public GameSessionGoalRecord value3(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public GameSessionGoalRecord value4(Integer value) {
        setGoalId(value);
        return this;
    }

    @Override
    public GameSessionGoalRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameSessionGoalRecord
     */
    public GameSessionGoalRecord() {
        super(GameSessionGoal.GAME_SESSION_GOAL);
    }

    /**
     * Create a detached, initialised GameSessionGoalRecord
     */
    public GameSessionGoalRecord(Integer id, String explanation, Integer gameSessionId, Integer goalId) {
        super(GameSessionGoal.GAME_SESSION_GOAL);

        setId(id);
        setExplanation(explanation);
        setGameSessionId(gameSessionId);
        setGoalId(goalId);
        resetChangedOnNotNull();
    }
}
