/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.HandlerType;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HandlerTypeRecord extends UpdatableRecordImpl<HandlerTypeRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.handler_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.handler_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.handler_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.handler_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.handler_type.java_type</code>.
     */
    public void setJavaType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.handler_type.java_type</code>.
     */
    public String getJavaType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gscg.handler_type.role_type_id</code>.
     */
    public void setRoleTypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.handler_type.role_type_id</code>.
     */
    public Integer getRoleTypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gscg.handler_type.content_type_id</code>.
     */
    public void setContentTypeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.handler_type.content_type_id</code>.
     */
    public Integer getContentTypeId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return HandlerType.HANDLER_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return HandlerType.HANDLER_TYPE.NAME;
    }

    @Override
    public Field<String> field3() {
        return HandlerType.HANDLER_TYPE.JAVA_TYPE;
    }

    @Override
    public Field<Integer> field4() {
        return HandlerType.HANDLER_TYPE.ROLE_TYPE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return HandlerType.HANDLER_TYPE.CONTENT_TYPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getJavaType();
    }

    @Override
    public Integer component4() {
        return getRoleTypeId();
    }

    @Override
    public Integer component5() {
        return getContentTypeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getJavaType();
    }

    @Override
    public Integer value4() {
        return getRoleTypeId();
    }

    @Override
    public Integer value5() {
        return getContentTypeId();
    }

    @Override
    public HandlerTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HandlerTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public HandlerTypeRecord value3(String value) {
        setJavaType(value);
        return this;
    }

    @Override
    public HandlerTypeRecord value4(Integer value) {
        setRoleTypeId(value);
        return this;
    }

    @Override
    public HandlerTypeRecord value5(Integer value) {
        setContentTypeId(value);
        return this;
    }

    @Override
    public HandlerTypeRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HandlerTypeRecord
     */
    public HandlerTypeRecord() {
        super(HandlerType.HANDLER_TYPE);
    }

    /**
     * Create a detached, initialised HandlerTypeRecord
     */
    public HandlerTypeRecord(Integer id, String name, String javaType, Integer roleTypeId, Integer contentTypeId) {
        super(HandlerType.HANDLER_TYPE);

        setId(id);
        setName(name);
        setJavaType(javaType);
        setRoleTypeId(roleTypeId);
        setContentTypeId(contentTypeId);
        resetChangedOnNotNull();
    }
}
