/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.Landmass;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LandmassRecord extends UpdatableRecordImpl<LandmassRecord> implements Record6<Integer, String, Double, Double, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.landmass.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.landmass.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.landmass.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.landmass.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.landmass.loc_x</code>.
     */
    public void setLocX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.landmass.loc_x</code>.
     */
    public Double getLocX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>gscg.landmass.loc_y</code>.
     */
    public void setLocY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.landmass.loc_y</code>.
     */
    public Double getLocY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>gscg.landmass.truck_speed</code>.
     */
    public void setTruckSpeed(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.landmass.truck_speed</code>.
     */
    public Double getTruckSpeed() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>gscg.landmass.speed_unit</code>.
     */
    public void setSpeedUnit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.landmass.speed_unit</code>.
     */
    public String getSpeedUnit() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Double, Double, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Double, Double, Double, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Landmass.LANDMASS.ID;
    }

    @Override
    public Field<String> field2() {
        return Landmass.LANDMASS.NAME;
    }

    @Override
    public Field<Double> field3() {
        return Landmass.LANDMASS.LOC_X;
    }

    @Override
    public Field<Double> field4() {
        return Landmass.LANDMASS.LOC_Y;
    }

    @Override
    public Field<Double> field5() {
        return Landmass.LANDMASS.TRUCK_SPEED;
    }

    @Override
    public Field<String> field6() {
        return Landmass.LANDMASS.SPEED_UNIT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getLocX();
    }

    @Override
    public Double component4() {
        return getLocY();
    }

    @Override
    public Double component5() {
        return getTruckSpeed();
    }

    @Override
    public String component6() {
        return getSpeedUnit();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getLocX();
    }

    @Override
    public Double value4() {
        return getLocY();
    }

    @Override
    public Double value5() {
        return getTruckSpeed();
    }

    @Override
    public String value6() {
        return getSpeedUnit();
    }

    @Override
    public LandmassRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LandmassRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LandmassRecord value3(Double value) {
        setLocX(value);
        return this;
    }

    @Override
    public LandmassRecord value4(Double value) {
        setLocY(value);
        return this;
    }

    @Override
    public LandmassRecord value5(Double value) {
        setTruckSpeed(value);
        return this;
    }

    @Override
    public LandmassRecord value6(String value) {
        setSpeedUnit(value);
        return this;
    }

    @Override
    public LandmassRecord values(Integer value1, String value2, Double value3, Double value4, Double value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LandmassRecord
     */
    public LandmassRecord() {
        super(Landmass.LANDMASS);
    }

    /**
     * Create a detached, initialised LandmassRecord
     */
    public LandmassRecord(Integer id, String name, Double locX, Double locY, Double truckSpeed, String speedUnit) {
        super(Landmass.LANDMASS);

        setId(id);
        setName(name);
        setLocX(locX);
        setLocY(locY);
        setTruckSpeed(truckSpeed);
        setSpeedUnit(speedUnit);
        resetChangedOnNotNull();
    }
}
