/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.Location;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record6<Integer, String, Double, Double, Double, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.location.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.location.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.location.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.location.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.location.loc_x</code>.
     */
    public void setLocX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.location.loc_x</code>.
     */
    public Double getLocX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>gscg.location.loc_y</code>.
     */
    public void setLocY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.location.loc_y</code>.
     */
    public Double getLocY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>gscg.location.timezone_offset</code>.
     */
    public void setTimezoneOffset(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>gscg.location.timezone_offset</code>.
     */
    public Double getTimezoneOffset() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>gscg.location.landmass_id</code>.
     */
    public void setLandmassId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gscg.location.landmass_id</code>.
     */
    public Integer getLandmassId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Double, Double, Double, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Double, Double, Double, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Location.LOCATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Location.LOCATION.NAME;
    }

    @Override
    public Field<Double> field3() {
        return Location.LOCATION.LOC_X;
    }

    @Override
    public Field<Double> field4() {
        return Location.LOCATION.LOC_Y;
    }

    @Override
    public Field<Double> field5() {
        return Location.LOCATION.TIMEZONE_OFFSET;
    }

    @Override
    public Field<Integer> field6() {
        return Location.LOCATION.LANDMASS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getLocX();
    }

    @Override
    public Double component4() {
        return getLocY();
    }

    @Override
    public Double component5() {
        return getTimezoneOffset();
    }

    @Override
    public Integer component6() {
        return getLandmassId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getLocX();
    }

    @Override
    public Double value4() {
        return getLocY();
    }

    @Override
    public Double value5() {
        return getTimezoneOffset();
    }

    @Override
    public Integer value6() {
        return getLandmassId();
    }

    @Override
    public LocationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LocationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LocationRecord value3(Double value) {
        setLocX(value);
        return this;
    }

    @Override
    public LocationRecord value4(Double value) {
        setLocY(value);
        return this;
    }

    @Override
    public LocationRecord value5(Double value) {
        setTimezoneOffset(value);
        return this;
    }

    @Override
    public LocationRecord value6(Integer value) {
        setLandmassId(value);
        return this;
    }

    @Override
    public LocationRecord values(Integer value1, String value2, Double value3, Double value4, Double value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Integer id, String name, Double locX, Double locY, Double timezoneOffset, Integer landmassId) {
        super(Location.LOCATION);

        setId(id);
        setName(name);
        setLocX(locX);
        setLocY(locY);
        setTimezoneOffset(timezoneOffset);
        setLandmassId(landmassId);
        resetChangedOnNotNull();
    }
}
