/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.NewsActor;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsActorRecord extends UpdatableRecordImpl<NewsActorRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.news_actor.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.news_actor.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.news_actor.news_message_id</code>.
     */
    public void setNewsMessageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.news_actor.news_message_id</code>.
     */
    public Integer getNewsMessageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gscg.news_actor.actor_id</code>.
     */
    public void setActorId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.news_actor.actor_id</code>.
     */
    public Integer getActorId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NewsActor.NEWS_ACTOR.ID;
    }

    @Override
    public Field<Integer> field2() {
        return NewsActor.NEWS_ACTOR.NEWS_MESSAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return NewsActor.NEWS_ACTOR.ACTOR_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getNewsMessageId();
    }

    @Override
    public Integer component3() {
        return getActorId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getNewsMessageId();
    }

    @Override
    public Integer value3() {
        return getActorId();
    }

    @Override
    public NewsActorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NewsActorRecord value2(Integer value) {
        setNewsMessageId(value);
        return this;
    }

    @Override
    public NewsActorRecord value3(Integer value) {
        setActorId(value);
        return this;
    }

    @Override
    public NewsActorRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsActorRecord
     */
    public NewsActorRecord() {
        super(NewsActor.NEWS_ACTOR);
    }

    /**
     * Create a detached, initialised NewsActorRecord
     */
    public NewsActorRecord(Integer id, Integer newsMessageId, Integer actorId) {
        super(NewsActor.NEWS_ACTOR);

        setId(id);
        setNewsMessageId(newsMessageId);
        setActorId(actorId);
        resetChangedOnNotNull();
    }
}
