/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.OrganizationRole;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationRoleRecord extends UpdatableRecordImpl<OrganizationRoleRecord> implements Record4<Integer, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.organization_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.organization_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.organization_role.admin</code>.
     */
    public void setAdmin(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.organization_role.admin</code>.
     */
    public Byte getAdmin() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gscg.organization_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.organization_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gscg.organization_role.organization_id</code>.
     */
    public void setOrganizationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.organization_role.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Byte, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Byte, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrganizationRole.ORGANIZATION_ROLE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return OrganizationRole.ORGANIZATION_ROLE.ADMIN;
    }

    @Override
    public Field<Integer> field3() {
        return OrganizationRole.ORGANIZATION_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return OrganizationRole.ORGANIZATION_ROLE.ORGANIZATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getAdmin();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getOrganizationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getAdmin();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getOrganizationId();
    }

    @Override
    public OrganizationRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrganizationRoleRecord value2(Byte value) {
        setAdmin(value);
        return this;
    }

    @Override
    public OrganizationRoleRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public OrganizationRoleRecord value4(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public OrganizationRoleRecord values(Integer value1, Byte value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationRoleRecord
     */
    public OrganizationRoleRecord() {
        super(OrganizationRole.ORGANIZATION_ROLE);
    }

    /**
     * Create a detached, initialised OrganizationRoleRecord
     */
    public OrganizationRoleRecord(Integer id, Byte admin, Integer userId, Integer organizationId) {
        super(OrganizationRole.ORGANIZATION_ROLE);

        setId(id);
        setAdmin(admin);
        setUserId(userId);
        setOrganizationId(organizationId);
        resetChangedOnNotNull();
    }
}
