/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.ParameterType;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParameterTypeRecord extends UpdatableRecordImpl<ParameterTypeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.parameter_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.parameter_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.parameter_type.java_name</code>.
     */
    public void setJavaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.parameter_type.java_name</code>.
     */
    public String getJavaName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ParameterType.PARAMETER_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return ParameterType.PARAMETER_TYPE.JAVA_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getJavaName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getJavaName();
    }

    @Override
    public ParameterTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ParameterTypeRecord value2(String value) {
        setJavaName(value);
        return this;
    }

    @Override
    public ParameterTypeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParameterTypeRecord
     */
    public ParameterTypeRecord() {
        super(ParameterType.PARAMETER_TYPE);
    }

    /**
     * Create a detached, initialised ParameterTypeRecord
     */
    public ParameterTypeRecord(Integer id, String javaName) {
        super(ParameterType.PARAMETER_TYPE);

        setId(id);
        setJavaName(javaName);
        resetChangedOnNotNull();
    }
}
