/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables.records;


import org.gscg.data.tables.Process;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessRecord extends UpdatableRecordImpl<ProcessRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gscg.process.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gscg.process.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gscg.process.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gscg.process.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gscg.process.process_type_id</code>.
     */
    public void setProcessTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gscg.process.process_type_id</code>.
     */
    public Integer getProcessTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gscg.process.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gscg.process.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Process.PROCESS.ID;
    }

    @Override
    public Field<String> field2() {
        return Process.PROCESS.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Process.PROCESS.PROCESS_TYPE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Process.PROCESS.ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getProcessTypeId();
    }

    @Override
    public Integer component4() {
        return getRoleId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getProcessTypeId();
    }

    @Override
    public Integer value4() {
        return getRoleId();
    }

    @Override
    public ProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProcessRecord value3(Integer value) {
        setProcessTypeId(value);
        return this;
    }

    @Override
    public ProcessRecord value4(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public ProcessRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessRecord
     */
    public ProcessRecord() {
        super(Process.PROCESS);
    }

    /**
     * Create a detached, initialised ProcessRecord
     */
    public ProcessRecord(Integer id, String name, Integer processTypeId, Integer roleId) {
        super(Process.PROCESS);

        setId(id);
        setName(name);
        setProcessTypeId(processTypeId);
        setRoleId(roleId);
        resetChangedOnNotNull();
    }
}
