/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.ActorValueRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorValue extends TableImpl<ActorValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.actor_value</code>
     */
    public static final ActorValue ACTOR_VALUE = new ActorValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActorValueRecord> getRecordType() {
        return ActorValueRecord.class;
    }

    /**
     * The column <code>gscg.actor_value.id</code>.
     */
    public final TableField<ActorValueRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.actor_value.value</code>.
     */
    public final TableField<ActorValueRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gscg.actor_value.actor_parameter_id</code>.
     */
    public final TableField<ActorValueRecord, Integer> ACTOR_PARAMETER_ID = createField(DSL.name("actor_parameter_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gscg.actor_value.actor_id</code>.
     */
    public final TableField<ActorValueRecord, Integer> ACTOR_ID = createField(DSL.name("actor_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ActorValue(Name alias, Table<ActorValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActorValue(Name alias, Table<ActorValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.actor_value</code> table reference
     */
    public ActorValue(String alias) {
        this(DSL.name(alias), ACTOR_VALUE);
    }

    /**
     * Create an aliased <code>gscg.actor_value</code> table reference
     */
    public ActorValue(Name alias) {
        this(alias, ACTOR_VALUE);
    }

    /**
     * Create a <code>gscg.actor_value</code> table reference
     */
    public ActorValue() {
        this(DSL.name("actor_value"), null);
    }

    public <O extends Record> ActorValue(Table<O> child, ForeignKey<O, ActorValueRecord> key) {
        super(child, key, ACTOR_VALUE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACTOR_VALUE_FK_ACTOR_VALUE_ACTOR1_IDX, Indexes.ACTOR_VALUE_FK_ACTOR_VALUE_ACTOR_PARAMETER1_IDX);
    }

    @Override
    public Identity<ActorValueRecord, Integer> getIdentity() {
        return (Identity<ActorValueRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActorValueRecord> getPrimaryKey() {
        return Keys.KEY_ACTOR_VALUE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ActorValueRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACTOR_VALUE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ActorValueRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ACTOR_VALUE_ACTOR_PARAMETER1, Keys.FK_ACTOR_VALUE_ACTOR1);
    }

    private transient ActorParameter _actorParameter;
    private transient Actor _actor;

    /**
     * Get the implicit join path to the <code>gscg.actor_parameter</code>
     * table.
     */
    public ActorParameter actorParameter() {
        if (_actorParameter == null)
            _actorParameter = new ActorParameter(this, Keys.FK_ACTOR_VALUE_ACTOR_PARAMETER1);

        return _actorParameter;
    }

    /**
     * Get the implicit join path to the <code>gscg.actor</code> table.
     */
    public Actor actor() {
        if (_actor == null)
            _actor = new Actor(this, Keys.FK_ACTOR_VALUE_ACTOR1);

        return _actor;
    }

    @Override
    public ActorValue as(String alias) {
        return new ActorValue(DSL.name(alias), this);
    }

    @Override
    public ActorValue as(Name alias) {
        return new ActorValue(alias, this);
    }

    @Override
    public ActorValue as(Table<?> alias) {
        return new ActorValue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActorValue rename(String name) {
        return new ActorValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActorValue rename(Name name) {
        return new ActorValue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActorValue rename(Table<?> name) {
        return new ActorValue(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
