/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.BomItemRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BomItem extends TableImpl<BomItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.bom_item</code>
     */
    public static final BomItem BOM_ITEM = new BomItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BomItemRecord> getRecordType() {
        return BomItemRecord.class;
    }

    /**
     * The column <code>gscg.bom_item.id</code>.
     */
    public final TableField<BomItemRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.bom_item.amount</code>.
     */
    public final TableField<BomItemRecord, Double> AMOUNT = createField(DSL.name("amount"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>gscg.bom_item.product_id</code>.
     */
    public final TableField<BomItemRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gscg.bom_item.bill_of_materials_id</code>.
     */
    public final TableField<BomItemRecord, Integer> BILL_OF_MATERIALS_ID = createField(DSL.name("bill_of_materials_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private BomItem(Name alias, Table<BomItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private BomItem(Name alias, Table<BomItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.bom_item</code> table reference
     */
    public BomItem(String alias) {
        this(DSL.name(alias), BOM_ITEM);
    }

    /**
     * Create an aliased <code>gscg.bom_item</code> table reference
     */
    public BomItem(Name alias) {
        this(alias, BOM_ITEM);
    }

    /**
     * Create a <code>gscg.bom_item</code> table reference
     */
    public BomItem() {
        this(DSL.name("bom_item"), null);
    }

    public <O extends Record> BomItem(Table<O> child, ForeignKey<O, BomItemRecord> key) {
        super(child, key, BOM_ITEM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BOM_ITEM_FK_BOM_ITEM_BILL_OF_MATERIALS1_IDX, Indexes.BOM_ITEM_FK_BOM_ITEM_PRODUCT1_IDX);
    }

    @Override
    public Identity<BomItemRecord, Integer> getIdentity() {
        return (Identity<BomItemRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BomItemRecord> getPrimaryKey() {
        return Keys.KEY_BOM_ITEM_PRIMARY;
    }

    @Override
    public List<UniqueKey<BomItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BOM_ITEM_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<BomItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_BOM_ITEM_PRODUCT1, Keys.FK_BOM_ITEM_BILL_OF_MATERIALS1);
    }

    private transient Product _product;
    private transient BillOfMaterials _billOfMaterials;

    /**
     * Get the implicit join path to the <code>gscg.product</code> table.
     */
    public Product product() {
        if (_product == null)
            _product = new Product(this, Keys.FK_BOM_ITEM_PRODUCT1);

        return _product;
    }

    /**
     * Get the implicit join path to the <code>gscg.bill_of_materials</code>
     * table.
     */
    public BillOfMaterials billOfMaterials() {
        if (_billOfMaterials == null)
            _billOfMaterials = new BillOfMaterials(this, Keys.FK_BOM_ITEM_BILL_OF_MATERIALS1);

        return _billOfMaterials;
    }

    @Override
    public BomItem as(String alias) {
        return new BomItem(DSL.name(alias), this);
    }

    @Override
    public BomItem as(Name alias) {
        return new BomItem(alias, this);
    }

    @Override
    public BomItem as(Table<?> alias) {
        return new BomItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BomItem rename(String name) {
        return new BomItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BomItem rename(Name name) {
        return new BomItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BomItem rename(Table<?> name) {
        return new BomItem(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Double, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super Double, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super Double, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
