/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.ExtraNewsMessageRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExtraNewsMessage extends TableImpl<ExtraNewsMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.extra_news_message</code>
     */
    public static final ExtraNewsMessage EXTRA_NEWS_MESSAGE = new ExtraNewsMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExtraNewsMessageRecord> getRecordType() {
        return ExtraNewsMessageRecord.class;
    }

    /**
     * The column <code>gscg.extra_news_message.id</code>.
     */
    public final TableField<ExtraNewsMessageRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.extra_news_message.game_time</code>.
     */
    public final TableField<ExtraNewsMessageRecord, LocalDateTime> GAME_TIME = createField(DSL.name("game_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>gscg.extra_news_message.wall_time</code>.
     */
    public final TableField<ExtraNewsMessageRecord, LocalDateTime> WALL_TIME = createField(DSL.name("wall_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>gscg.extra_news_message.header</code>.
     */
    public final TableField<ExtraNewsMessageRecord, String> HEADER = createField(DSL.name("header"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.extra_news_message.content</code>.
     */
    public final TableField<ExtraNewsMessageRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gscg.extra_news_message.game_session_id</code>.
     */
    public final TableField<ExtraNewsMessageRecord, Integer> GAME_SESSION_ID = createField(DSL.name("game_session_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ExtraNewsMessage(Name alias, Table<ExtraNewsMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExtraNewsMessage(Name alias, Table<ExtraNewsMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.extra_news_message</code> table reference
     */
    public ExtraNewsMessage(String alias) {
        this(DSL.name(alias), EXTRA_NEWS_MESSAGE);
    }

    /**
     * Create an aliased <code>gscg.extra_news_message</code> table reference
     */
    public ExtraNewsMessage(Name alias) {
        this(alias, EXTRA_NEWS_MESSAGE);
    }

    /**
     * Create a <code>gscg.extra_news_message</code> table reference
     */
    public ExtraNewsMessage() {
        this(DSL.name("extra_news_message"), null);
    }

    public <O extends Record> ExtraNewsMessage(Table<O> child, ForeignKey<O, ExtraNewsMessageRecord> key) {
        super(child, key, EXTRA_NEWS_MESSAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EXTRA_NEWS_MESSAGE_FK_EXTRA_NEWS_MESSAGE_GAME_SESSION1_IDX);
    }

    @Override
    public Identity<ExtraNewsMessageRecord, Integer> getIdentity() {
        return (Identity<ExtraNewsMessageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ExtraNewsMessageRecord> getPrimaryKey() {
        return Keys.KEY_EXTRA_NEWS_MESSAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ExtraNewsMessageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_EXTRA_NEWS_MESSAGE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ExtraNewsMessageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_EXTRA_NEWS_MESSAGE_GAME_SESSION1);
    }

    private transient GameSession _gameSession;

    /**
     * Get the implicit join path to the <code>gscg.game_session</code> table.
     */
    public GameSession gameSession() {
        if (_gameSession == null)
            _gameSession = new GameSession(this, Keys.FK_EXTRA_NEWS_MESSAGE_GAME_SESSION1);

        return _gameSession;
    }

    @Override
    public ExtraNewsMessage as(String alias) {
        return new ExtraNewsMessage(DSL.name(alias), this);
    }

    @Override
    public ExtraNewsMessage as(Name alias) {
        return new ExtraNewsMessage(alias, this);
    }

    @Override
    public ExtraNewsMessage as(Table<?> alias) {
        return new ExtraNewsMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtraNewsMessage rename(String name) {
        return new ExtraNewsMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtraNewsMessage rename(Name name) {
        return new ExtraNewsMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExtraNewsMessage rename(Table<?> name) {
        return new ExtraNewsMessage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, LocalDateTime, LocalDateTime, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
