/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.HandlerValueRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HandlerValue extends TableImpl<HandlerValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.handler_value</code>
     */
    public static final HandlerValue HANDLER_VALUE = new HandlerValue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HandlerValueRecord> getRecordType() {
        return HandlerValueRecord.class;
    }

    /**
     * The column <code>gscg.handler_value.id</code>.
     */
    public final TableField<HandlerValueRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.handler_value.value</code>.
     */
    public final TableField<HandlerValueRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gscg.handler_value.handler_parameter_id</code>.
     */
    public final TableField<HandlerValueRecord, Integer> HANDLER_PARAMETER_ID = createField(DSL.name("handler_parameter_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gscg.handler_value.handler_id</code>.
     */
    public final TableField<HandlerValueRecord, Integer> HANDLER_ID = createField(DSL.name("handler_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private HandlerValue(Name alias, Table<HandlerValueRecord> aliased) {
        this(alias, aliased, null);
    }

    private HandlerValue(Name alias, Table<HandlerValueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.handler_value</code> table reference
     */
    public HandlerValue(String alias) {
        this(DSL.name(alias), HANDLER_VALUE);
    }

    /**
     * Create an aliased <code>gscg.handler_value</code> table reference
     */
    public HandlerValue(Name alias) {
        this(alias, HANDLER_VALUE);
    }

    /**
     * Create a <code>gscg.handler_value</code> table reference
     */
    public HandlerValue() {
        this(DSL.name("handler_value"), null);
    }

    public <O extends Record> HandlerValue(Table<O> child, ForeignKey<O, HandlerValueRecord> key) {
        super(child, key, HANDLER_VALUE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HANDLER_VALUE_FK_HANDLER_VALUE_HANDLER1_IDX, Indexes.HANDLER_VALUE_FK_HANDLER_VALUE_HANDLER_PARAMETER1_IDX);
    }

    @Override
    public Identity<HandlerValueRecord, Integer> getIdentity() {
        return (Identity<HandlerValueRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HandlerValueRecord> getPrimaryKey() {
        return Keys.KEY_HANDLER_VALUE_PRIMARY;
    }

    @Override
    public List<UniqueKey<HandlerValueRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HANDLER_VALUE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<HandlerValueRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_HANDLER_VALUE_HANDLER_PARAMETER1, Keys.FK_HANDLER_VALUE_HANDLER1);
    }

    private transient HandlerParameter _handlerParameter;
    private transient Handler _handler;

    /**
     * Get the implicit join path to the <code>gscg.handler_parameter</code>
     * table.
     */
    public HandlerParameter handlerParameter() {
        if (_handlerParameter == null)
            _handlerParameter = new HandlerParameter(this, Keys.FK_HANDLER_VALUE_HANDLER_PARAMETER1);

        return _handlerParameter;
    }

    /**
     * Get the implicit join path to the <code>gscg.handler</code> table.
     */
    public Handler handler() {
        if (_handler == null)
            _handler = new Handler(this, Keys.FK_HANDLER_VALUE_HANDLER1);

        return _handler;
    }

    @Override
    public HandlerValue as(String alias) {
        return new HandlerValue(DSL.name(alias), this);
    }

    @Override
    public HandlerValue as(Name alias) {
        return new HandlerValue(alias, this);
    }

    @Override
    public HandlerValue as(Table<?> alias) {
        return new HandlerValue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HandlerValue rename(String name) {
        return new HandlerValue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HandlerValue rename(Name name) {
        return new HandlerValue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HandlerValue rename(Table<?> name) {
        return new HandlerValue(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
