/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.HandlerRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Handler extends TableImpl<HandlerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.handler</code>
     */
    public static final Handler HANDLER = new Handler();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HandlerRecord> getRecordType() {
        return HandlerRecord.class;
    }

    /**
     * The column <code>gscg.handler.id</code>.
     */
    public final TableField<HandlerRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.handler.name</code>.
     */
    public final TableField<HandlerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.handler.handler_type_id</code>.
     */
    public final TableField<HandlerRecord, Integer> HANDLER_TYPE_ID = createField(DSL.name("handler_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gscg.handler.role_id</code>.
     */
    public final TableField<HandlerRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Handler(Name alias, Table<HandlerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Handler(Name alias, Table<HandlerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.handler</code> table reference
     */
    public Handler(String alias) {
        this(DSL.name(alias), HANDLER);
    }

    /**
     * Create an aliased <code>gscg.handler</code> table reference
     */
    public Handler(Name alias) {
        this(alias, HANDLER);
    }

    /**
     * Create a <code>gscg.handler</code> table reference
     */
    public Handler() {
        this(DSL.name("handler"), null);
    }

    public <O extends Record> Handler(Table<O> child, ForeignKey<O, HandlerRecord> key) {
        super(child, key, HANDLER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HANDLER_FK_HANDLER_HANDLER_TYPE1_IDX, Indexes.HANDLER_FK_HANDLER_ROLE1_IDX);
    }

    @Override
    public Identity<HandlerRecord, Integer> getIdentity() {
        return (Identity<HandlerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HandlerRecord> getPrimaryKey() {
        return Keys.KEY_HANDLER_PRIMARY;
    }

    @Override
    public List<UniqueKey<HandlerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_HANDLER_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<HandlerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_HANDLER_HANDLER_TYPE1, Keys.FK_HANDLER_ROLE1);
    }

    private transient HandlerType _handlerType;
    private transient Role _role;

    /**
     * Get the implicit join path to the <code>gscg.handler_type</code> table.
     */
    public HandlerType handlerType() {
        if (_handlerType == null)
            _handlerType = new HandlerType(this, Keys.FK_HANDLER_HANDLER_TYPE1);

        return _handlerType;
    }

    /**
     * Get the implicit join path to the <code>gscg.role</code> table.
     */
    public Role role() {
        if (_role == null)
            _role = new Role(this, Keys.FK_HANDLER_ROLE1);

        return _role;
    }

    @Override
    public Handler as(String alias) {
        return new Handler(DSL.name(alias), this);
    }

    @Override
    public Handler as(Name alias) {
        return new Handler(alias, this);
    }

    @Override
    public Handler as(Table<?> alias) {
        return new Handler(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Handler rename(String name) {
        return new Handler(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Handler rename(Name name) {
        return new Handler(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Handler rename(Table<?> name) {
        return new Handler(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
