/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.ListPageRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListPage extends TableImpl<ListPageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.list_page</code>
     */
    public static final ListPage LIST_PAGE = new ListPage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ListPageRecord> getRecordType() {
        return ListPageRecord.class;
    }

    /**
     * The column <code>gscg.list_page.id</code>.
     */
    public final TableField<ListPageRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.list_page.name</code>.
     */
    public final TableField<ListPageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.list_page.html</code>.
     */
    public final TableField<ListPageRecord, String> HTML = createField(DSL.name("html"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gscg.list_page.page_list_id</code>.
     */
    public final TableField<ListPageRecord, Integer> PAGE_LIST_ID = createField(DSL.name("page_list_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ListPage(Name alias, Table<ListPageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ListPage(Name alias, Table<ListPageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.list_page</code> table reference
     */
    public ListPage(String alias) {
        this(DSL.name(alias), LIST_PAGE);
    }

    /**
     * Create an aliased <code>gscg.list_page</code> table reference
     */
    public ListPage(Name alias) {
        this(alias, LIST_PAGE);
    }

    /**
     * Create a <code>gscg.list_page</code> table reference
     */
    public ListPage() {
        this(DSL.name("list_page"), null);
    }

    public <O extends Record> ListPage(Table<O> child, ForeignKey<O, ListPageRecord> key) {
        super(child, key, LIST_PAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.LIST_PAGE_FK_PAGE_PAGE_LIST1_IDX);
    }

    @Override
    public Identity<ListPageRecord, Integer> getIdentity() {
        return (Identity<ListPageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ListPageRecord> getPrimaryKey() {
        return Keys.KEY_LIST_PAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ListPageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_LIST_PAGE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ListPageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PAGE_PAGE_LIST1);
    }

    private transient PageList _pageList;

    /**
     * Get the implicit join path to the <code>gscg.page_list</code> table.
     */
    public PageList pageList() {
        if (_pageList == null)
            _pageList = new PageList(this, Keys.FK_PAGE_PAGE_LIST1);

        return _pageList;
    }

    @Override
    public ListPage as(String alias) {
        return new ListPage(DSL.name(alias), this);
    }

    @Override
    public ListPage as(Name alias) {
        return new ListPage(alias, this);
    }

    @Override
    public ListPage as(Table<?> alias) {
        return new ListPage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ListPage rename(String name) {
        return new ListPage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListPage rename(Name name) {
        return new ListPage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ListPage rename(Table<?> name) {
        return new ListPage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
