/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.NewsActorTypeRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsActorType extends TableImpl<NewsActorTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.news_actor_type</code>
     */
    public static final NewsActorType NEWS_ACTOR_TYPE = new NewsActorType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewsActorTypeRecord> getRecordType() {
        return NewsActorTypeRecord.class;
    }

    /**
     * The column <code>gscg.news_actor_type.id</code>.
     */
    public final TableField<NewsActorTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.news_actor_type.news_message_id</code>.
     */
    public final TableField<NewsActorTypeRecord, Integer> NEWS_MESSAGE_ID = createField(DSL.name("news_message_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gscg.news_actor_type.actor_type_id</code>.
     */
    public final TableField<NewsActorTypeRecord, Integer> ACTOR_TYPE_ID = createField(DSL.name("actor_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private NewsActorType(Name alias, Table<NewsActorTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private NewsActorType(Name alias, Table<NewsActorTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.news_actor_type</code> table reference
     */
    public NewsActorType(String alias) {
        this(DSL.name(alias), NEWS_ACTOR_TYPE);
    }

    /**
     * Create an aliased <code>gscg.news_actor_type</code> table reference
     */
    public NewsActorType(Name alias) {
        this(alias, NEWS_ACTOR_TYPE);
    }

    /**
     * Create a <code>gscg.news_actor_type</code> table reference
     */
    public NewsActorType() {
        this(DSL.name("news_actor_type"), null);
    }

    public <O extends Record> NewsActorType(Table<O> child, ForeignKey<O, NewsActorTypeRecord> key) {
        super(child, key, NEWS_ACTOR_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.NEWS_ACTOR_TYPE_FK_NEWS_ACTOR_TYPE_ACTOR_TYPE1_IDX, Indexes.NEWS_ACTOR_TYPE_FK_NEWS_ACTOR_TYPE_NEWS_MESSAGE1_IDX);
    }

    @Override
    public Identity<NewsActorTypeRecord, Integer> getIdentity() {
        return (Identity<NewsActorTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NewsActorTypeRecord> getPrimaryKey() {
        return Keys.KEY_NEWS_ACTOR_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<NewsActorTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_NEWS_ACTOR_TYPE_D_UNIQUE);
    }

    @Override
    public List<ForeignKey<NewsActorTypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_NEWS_ACTOR_TYPE_NEWS_MESSAGE1, Keys.FK_NEWS_ACTOR_TYPE_ACTOR_TYPE1);
    }

    private transient NewsMessage _newsMessage;
    private transient ActorType _actorType;

    /**
     * Get the implicit join path to the <code>gscg.news_message</code> table.
     */
    public NewsMessage newsMessage() {
        if (_newsMessage == null)
            _newsMessage = new NewsMessage(this, Keys.FK_NEWS_ACTOR_TYPE_NEWS_MESSAGE1);

        return _newsMessage;
    }

    /**
     * Get the implicit join path to the <code>gscg.actor_type</code> table.
     */
    public ActorType actorType() {
        if (_actorType == null)
            _actorType = new ActorType(this, Keys.FK_NEWS_ACTOR_TYPE_ACTOR_TYPE1);

        return _actorType;
    }

    @Override
    public NewsActorType as(String alias) {
        return new NewsActorType(DSL.name(alias), this);
    }

    @Override
    public NewsActorType as(Name alias) {
        return new NewsActorType(alias, this);
    }

    @Override
    public NewsActorType as(Table<?> alias) {
        return new NewsActorType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsActorType rename(String name) {
        return new NewsActorType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsActorType rename(Name name) {
        return new NewsActorType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsActorType rename(Table<?> name) {
        return new NewsActorType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
