/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.PageListRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageList extends TableImpl<PageListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.page_list</code>
     */
    public static final PageList PAGE_LIST = new PageList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PageListRecord> getRecordType() {
        return PageListRecord.class;
    }

    /**
     * The column <code>gscg.page_list.id</code>.
     */
    public final TableField<PageListRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.page_list.name</code>.
     */
    public final TableField<PageListRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.page_list.header_html</code>.
     */
    public final TableField<PageListRecord, String> HEADER_HTML = createField(DSL.name("header_html"), SQLDataType.CLOB.nullable(false), this, "");

    private PageList(Name alias, Table<PageListRecord> aliased) {
        this(alias, aliased, null);
    }

    private PageList(Name alias, Table<PageListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.page_list</code> table reference
     */
    public PageList(String alias) {
        this(DSL.name(alias), PAGE_LIST);
    }

    /**
     * Create an aliased <code>gscg.page_list</code> table reference
     */
    public PageList(Name alias) {
        this(alias, PAGE_LIST);
    }

    /**
     * Create a <code>gscg.page_list</code> table reference
     */
    public PageList() {
        this(DSL.name("page_list"), null);
    }

    public <O extends Record> PageList(Table<O> child, ForeignKey<O, PageListRecord> key) {
        super(child, key, PAGE_LIST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public Identity<PageListRecord, Integer> getIdentity() {
        return (Identity<PageListRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PageListRecord> getPrimaryKey() {
        return Keys.KEY_PAGE_LIST_PRIMARY;
    }

    @Override
    public List<UniqueKey<PageListRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PAGE_LIST_ID_UNIQUE);
    }

    @Override
    public PageList as(String alias) {
        return new PageList(DSL.name(alias), this);
    }

    @Override
    public PageList as(Name alias) {
        return new PageList(alias, this);
    }

    @Override
    public PageList as(Table<?> alias) {
        return new PageList(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PageList rename(String name) {
        return new PageList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PageList rename(Name name) {
        return new PageList(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PageList rename(Table<?> name) {
        return new PageList(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
