/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.PlayerDecisionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerDecision extends TableImpl<PlayerDecisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.player_decision</code>
     */
    public static final PlayerDecision PLAYER_DECISION = new PlayerDecision();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerDecisionRecord> getRecordType() {
        return PlayerDecisionRecord.class;
    }

    /**
     * The column <code>gscg.player_decision.id</code>.
     */
    public final TableField<PlayerDecisionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.player_decision.game_time</code>.
     */
    public final TableField<PlayerDecisionRecord, LocalDateTime> GAME_TIME = createField(DSL.name("game_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>gscg.player_decision.wall_time</code>.
     */
    public final TableField<PlayerDecisionRecord, LocalDateTime> WALL_TIME = createField(DSL.name("wall_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>gscg.player_decision.name</code>.
     */
    public final TableField<PlayerDecisionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.player_decision.state</code>.
     */
    public final TableField<PlayerDecisionRecord, String> STATE = createField(DSL.name("state"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>gscg.player_decision.player_id</code>.
     */
    public final TableField<PlayerDecisionRecord, Integer> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private PlayerDecision(Name alias, Table<PlayerDecisionRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerDecision(Name alias, Table<PlayerDecisionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.player_decision</code> table reference
     */
    public PlayerDecision(String alias) {
        this(DSL.name(alias), PLAYER_DECISION);
    }

    /**
     * Create an aliased <code>gscg.player_decision</code> table reference
     */
    public PlayerDecision(Name alias) {
        this(alias, PLAYER_DECISION);
    }

    /**
     * Create a <code>gscg.player_decision</code> table reference
     */
    public PlayerDecision() {
        this(DSL.name("player_decision"), null);
    }

    public <O extends Record> PlayerDecision(Table<O> child, ForeignKey<O, PlayerDecisionRecord> key) {
        super(child, key, PLAYER_DECISION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_DECISION_FK_CHOSEN_STRATEGY_PLAYER1_IDX);
    }

    @Override
    public Identity<PlayerDecisionRecord, Integer> getIdentity() {
        return (Identity<PlayerDecisionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerDecisionRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_DECISION_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlayerDecisionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PLAYER_DECISION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<PlayerDecisionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_CHOSEN_STRATEGY_PLAYER10);
    }

    private transient Player _player;

    /**
     * Get the implicit join path to the <code>gscg.player</code> table.
     */
    public Player player() {
        if (_player == null)
            _player = new Player(this, Keys.FK_CHOSEN_STRATEGY_PLAYER10);

        return _player;
    }

    @Override
    public PlayerDecision as(String alias) {
        return new PlayerDecision(DSL.name(alias), this);
    }

    @Override
    public PlayerDecision as(Name alias) {
        return new PlayerDecision(alias, this);
    }

    @Override
    public PlayerDecision as(Table<?> alias) {
        return new PlayerDecision(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerDecision rename(String name) {
        return new PlayerDecision(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerDecision rename(Name name) {
        return new PlayerDecision(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerDecision rename(Table<?> name) {
        return new PlayerDecision(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, LocalDateTime, LocalDateTime, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super LocalDateTime, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
