/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Indexes;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.ProcessTypeRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessType extends TableImpl<ProcessTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.process_type</code>
     */
    public static final ProcessType PROCESS_TYPE = new ProcessType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessTypeRecord> getRecordType() {
        return ProcessTypeRecord.class;
    }

    /**
     * The column <code>gscg.process_type.id</code>.
     */
    public final TableField<ProcessTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.process_type.name</code>.
     */
    public final TableField<ProcessTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.process_type.java_type</code>.
     */
    public final TableField<ProcessTypeRecord, String> JAVA_TYPE = createField(DSL.name("java_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>gscg.process_type.role_type_id</code>.
     */
    public final TableField<ProcessTypeRecord, Integer> ROLE_TYPE_ID = createField(DSL.name("role_type_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private ProcessType(Name alias, Table<ProcessTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessType(Name alias, Table<ProcessTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.process_type</code> table reference
     */
    public ProcessType(String alias) {
        this(DSL.name(alias), PROCESS_TYPE);
    }

    /**
     * Create an aliased <code>gscg.process_type</code> table reference
     */
    public ProcessType(Name alias) {
        this(alias, PROCESS_TYPE);
    }

    /**
     * Create a <code>gscg.process_type</code> table reference
     */
    public ProcessType() {
        this(DSL.name("process_type"), null);
    }

    public <O extends Record> ProcessType(Table<O> child, ForeignKey<O, ProcessTypeRecord> key) {
        super(child, key, PROCESS_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROCESS_TYPE_FK_PROCESS_TYPE_ROLE_TYPE1_IDX);
    }

    @Override
    public Identity<ProcessTypeRecord, Integer> getIdentity() {
        return (Identity<ProcessTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProcessTypeRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROCESS_TYPE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<ProcessTypeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROCESS_TYPE_ROLE_TYPE1);
    }

    private transient RoleType _roleType;

    /**
     * Get the implicit join path to the <code>gscg.role_type</code> table.
     */
    public RoleType roleType() {
        if (_roleType == null)
            _roleType = new RoleType(this, Keys.FK_PROCESS_TYPE_ROLE_TYPE1);

        return _roleType;
    }

    @Override
    public ProcessType as(String alias) {
        return new ProcessType(DSL.name(alias), this);
    }

    @Override
    public ProcessType as(Name alias) {
        return new ProcessType(alias, this);
    }

    @Override
    public ProcessType as(Table<?> alias) {
        return new ProcessType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessType rename(String name) {
        return new ProcessType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessType rename(Name name) {
        return new ProcessType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessType rename(Table<?> name) {
        return new ProcessType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
