/*
 * This file is generated by jOOQ.
 */
package org.gscg.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.gscg.data.Gscg;
import org.gscg.data.Keys;
import org.gscg.data.tables.records.TriggerIntervalRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TriggerInterval extends TableImpl<TriggerIntervalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gscg.trigger_interval</code>
     */
    public static final TriggerInterval TRIGGER_INTERVAL = new TriggerInterval();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TriggerIntervalRecord> getRecordType() {
        return TriggerIntervalRecord.class;
    }

    /**
     * The column <code>gscg.trigger_interval.id</code>.
     */
    public final TableField<TriggerIntervalRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gscg.trigger_interval.name</code>.
     */
    public final TableField<TriggerIntervalRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gscg.trigger_interval.timestamp_datetime_start</code>.
     */
    public final TableField<TriggerIntervalRecord, LocalDateTime> TIMESTAMP_DATETIME_START = createField(DSL.name("timestamp_datetime_start"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gscg.trigger_interval.timestamp_datetime_until</code>.
     */
    public final TableField<TriggerIntervalRecord, LocalDateTime> TIMESTAMP_DATETIME_UNTIL = createField(DSL.name("timestamp_datetime_until"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gscg.trigger_interval.timestamp_gametime_start</code>.
     */
    public final TableField<TriggerIntervalRecord, Double> TIMESTAMP_GAMETIME_START = createField(DSL.name("timestamp_gametime_start"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>gscg.trigger_interval.timestamp_gametime_until</code>.
     */
    public final TableField<TriggerIntervalRecord, Double> TIMESTAMP_GAMETIME_UNTIL = createField(DSL.name("timestamp_gametime_until"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>gscg.trigger_interval.timestamp_unit</code>.
     */
    public final TableField<TriggerIntervalRecord, String> TIMESTAMP_UNIT = createField(DSL.name("timestamp_unit"), SQLDataType.VARCHAR(10).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gscg.trigger_interval.facilitator_trigger</code>.
     */
    public final TableField<TriggerIntervalRecord, Byte> FACILITATOR_TRIGGER = createField(DSL.name("facilitator_trigger"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gscg.trigger_interval.trigger_once</code>.
     */
    public final TableField<TriggerIntervalRecord, Byte> TRIGGER_ONCE = createField(DSL.name("trigger_once"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "");

    private TriggerInterval(Name alias, Table<TriggerIntervalRecord> aliased) {
        this(alias, aliased, null);
    }

    private TriggerInterval(Name alias, Table<TriggerIntervalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gscg.trigger_interval</code> table reference
     */
    public TriggerInterval(String alias) {
        this(DSL.name(alias), TRIGGER_INTERVAL);
    }

    /**
     * Create an aliased <code>gscg.trigger_interval</code> table reference
     */
    public TriggerInterval(Name alias) {
        this(alias, TRIGGER_INTERVAL);
    }

    /**
     * Create a <code>gscg.trigger_interval</code> table reference
     */
    public TriggerInterval() {
        this(DSL.name("trigger_interval"), null);
    }

    public <O extends Record> TriggerInterval(Table<O> child, ForeignKey<O, TriggerIntervalRecord> key) {
        super(child, key, TRIGGER_INTERVAL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gscg.GSCG;
    }

    @Override
    public Identity<TriggerIntervalRecord, Integer> getIdentity() {
        return (Identity<TriggerIntervalRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TriggerIntervalRecord> getPrimaryKey() {
        return Keys.KEY_TRIGGER_INTERVAL_PRIMARY;
    }

    @Override
    public List<UniqueKey<TriggerIntervalRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TRIGGER_INTERVAL_ID_UNIQUE);
    }

    @Override
    public TriggerInterval as(String alias) {
        return new TriggerInterval(DSL.name(alias), this);
    }

    @Override
    public TriggerInterval as(Name alias) {
        return new TriggerInterval(alias, this);
    }

    @Override
    public TriggerInterval as(Table<?> alias) {
        return new TriggerInterval(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TriggerInterval rename(String name) {
        return new TriggerInterval(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TriggerInterval rename(Name name) {
        return new TriggerInterval(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TriggerInterval rename(Table<?> name) {
        return new TriggerInterval(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, LocalDateTime, LocalDateTime, Double, Double, String, Byte, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Double, ? super Double, ? super String, ? super Byte, ? super Byte, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super Double, ? super Double, ? super String, ? super Byte, ? super Byte, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
